### ISSUE TITLE
Add a codegen builder

### ISSUE THREAD

**Issue by danburkert** [danburkert/prost#10]
There are expected to be a few more optional features in the future: map type, service generator, zero copy, etc.

**Comment by valarauca** [comment]
I'm just passing by to :+1: this issue.

I'm using ProtoBufs in a Rust project for work and we currently have a monorepo that holds all our protobuffers (and a very long 200+ LoC `Makefile`) to build them I've spent a few hours to integrate this tool this morning and exposing a way to pass args to `--proto_path` is desperately needed via the `build.rs` file.

**Comment by danburkert** [comment]
@valarauca That's already possible, have you seen the docs in https://github.com/danburkert/prost/tree/master/prost-build README?  [`prost_build::compile_protos`](https://docs.rs/prost-build/0.1.0/prost_build/fn.compile_protos.html)'s second argument is the include paths.  Note that the protobuf builtin .protos are already included (the well known types stuff).

**Comment by valarauca** [comment]
I'm really not sure I understand (or I misstated my issue).

I'm attempting to retrofit `prost` into our my companies existing structure without breaking anything.

Structure example:

```
proto/
----Makefile
----build.gradle
----Gopkg.toml
----Gopkg.lock
-----team/
---------team.proto
-----another_team/
---------name1.proto
---------name2.proto
```

So this becomes

```
proto/
----Cargo.toml
----build.rs
----Makefile
----build.gradle
----Gopkg.toml
----Gopkg.lock
-----src/
---------lib.rs
---------item.rs #Hopefuly
-----team/
---------team.proto
-----another_team/
---------name1.proto
---------name2.proto
```

If I just do something like `prost_build::compile_protos(&["agent/agent.proto"], &[], None).unwrap()`

This fails as `agent.proto`'s package is `agent.proto` So I should do `prost_build::compile_protos(&[], &["agent/agent.proto"], None).unwrap()`?

---

I will try this but currently I cannot build `prost` requires `bytes = "0.1.2"` which requires nightly? I see `0.4` is called out, but `0.1.2` is always fetched by `cargo`. I attempted to fully purge my `~/.cargo/registry`

**Comment by danburkert** [comment]
Yes, this is currently supported.  The first arg to `compile_protos` is the list of `.proto`s you want to compile (you can skip any that are transitively imported, you only have to include the 'root' .protos).  The second arg is the include paths.  What the include paths should be depends on what the `package` declaration in the protobufs is, but assuming that's `package team;` and `package another_team;`, and we're compiling from the first source tree above, I think you want:

```rust
prost_build::compile_protos(&["src/team/team.proto"], &["src/"], None).unwrap()
```

**Comment by valarauca** [comment]
Awesome. Any clue what's up with the `bytes v0.1.2` being imported?

My first attempt it didn't happen, but on the 2nd, 3rd, and 4th it crashed and burned.

**Comment by danburkert** [comment]
hmm, no.  My usual route for debugging issues like that is to inspect Cargo.lock and figure out where they are coming from.  `prost` and `prost-build` have a dependency on 0.4, so it shouldn't be pulling in 0.1.

**Comment by valarauca** [comment]
Interesting.

I'll throw this in queue.

**Comment by danburkert** [comment]
A code generator config has been added in 17474e8139a4c8630a75930e22dbcfc173afab32.  @valarauca if you're still having build issues feel free to open another issue.
