### ISSUE TITLE
"warning: unused result" when using "#![warn(unused_results)]"

### ISSUE THREAD

**Issue by im-0** [danburkert/prost#101]
```
warning: unused result
  --> .../out/proto.rs:11:28
   |
11 | #[derive(Clone, PartialEq, Message)]
   |                            ^^^^^^^
   |
note: lint level defined here
  --> .../src/main.rs:2:9
   |
2  | #![warn(unused_results)]
   |         ^^^^^^^^^^^^^^
```

Deriving `Message` on structure which have fields is enough to trigger this warning. No warning on empty structures.

**Comment by danburkert** [comment]
Do you have a more complete repro?  It's going to be difficult to track this down without.  If not, are you using codegen, or is this a hand written struct?
