### ISSUE TITLE
Custom output directory?

### ISSUE THREAD

**Issue by gwihlidal** [danburkert/prost#115]
I am hoping to have prost write out the generated source files to a custom location (i.e. 'src' in my project), rather than a temp location (rust protoc has this option: https://github.com/stepancheg/rust-protobuf/blob/master/protoc-rust/src/lib.rs#L21)

Is this currently possible with prost? If not, it would be a very useful setting on the prost build config.

Thanks!

**Comment by gwihlidal** [comment]
Agree, I think relying on OUT_DIR exclusively isn't very approachable for all codebases. I would much rather have a builder-like api similar to protoc-rust.

**Comment by danburkert** [comment]
There is an existing builder api, `prost_build::Config`.  ab9fc6 adds a new option which allows configuring the output director.

**Comment by thedodd** [comment]
Any plans on cutting a release which includes the above?

**Comment by nrc** [comment]
@danburkert I too would love to get a new release of Prost including this change (although I guess I would love to get this and #147 even more).

**Comment by harscoet** [comment]
Documentation is missing so this is an example for your **build.rs** (from https://github.com/danburkert/snazzy/blob/master/build.rs)
```rust
extern crate prost_build; // Optional in 2018 edition

fn main() {
    let mut config = prost_build::Config::default();
    config.out_dir("src");

    config.compile_protos(&["src/items.proto"], &["src/"]).unwrap();
}
```
