### ISSUE TITLE
Initialise Message Without Populating all Fields

### ISSUE THREAD

**Issue by nevi-me** [danburkert/prost#121]
I'm using prost as a dependency on tower-grpc, but I'm struggling as I was using another protobuf implementation.

I have a protobuf message that has a lot of fields, and prost requires me to initialise all of them when creating the message. Is there an equivalent of `Message::new()` that would set default values? Sometimes I only want to set 1-2 fields out of a message that has much more, but it's so far cumbersome.

I'm using proto3 btw.

**Comment by nevi-me** [comment]
Thanks @per-gron, what does the `..Default::default()` magic do?

So then if I want an 'empty' message, can I do the below?

```rust
let mut message = myproto::Message {
  ..Default::default()
}
```

**Comment by per-gron** [comment]
It's not all that magic: it's a combination of the [`..` struct update syntax](https://doc.rust-lang.org/book/second-edition/ch05-01-defining-structs.html) and the [`Default` trait](https://doc.rust-lang.org/std/default/trait.Default.html).

The syntax you used in the previous comment should work, but you can also use only `Default` without struct update syntax:

```rust
let mut message : myproto::Message = Default::default();
```

if you just want a default value.
