### ISSUE TITLE
derive: use private const trick instead of modules

### ISSUE THREAD

**Issue by carllerche** [danburkert/prost#126]
It looks like prost [generates modules](https://github.com/danburkert/prost/blob/e6aaddc259409db2193b4eae6ac064fdea319fb6/prost-derive/src/lib.rs#L176) to contain impls.

The best strategy that I have found (by reading serde's source) is to use a private module to contain impls. This has the best hygiene. You can see how it is done [here](https://github.com/carllerche/tower-web/blob/master/tower-web-macros/src/derive/extract.rs#L61).

**Comment by carllerche** [comment]
Full disclosure, doing this means you must refer to all types using an absolute path as `use` statements don't seem to work. It is annoying, but the hygiene makes it worth it IMO.

**Comment by carllerche** [comment]
If this sounds good to you, I can work on a PR.

**Comment by danburkert** [comment]
Fixed in #185.
