### ISSUE TITLE
missing documentation for the `extension method`

### ISSUE THREAD

**Issue by yoshuawuyts** [danburkert/prost#130]
When generating structs with the `Message` header the generated code conflicts with the `#![deny(missing_docs)]` attribute. Because it occurs as part of a macro it results in a somewhat cryptic message.

## Solution
This can be solved by adding documentation to the resulting output, which should be fairly straight forward. Ideally a code example could be added too to be forward compatible with the `#![deny(missing_doc_code_examples)]` lint.

## Screenshots
![2018-10-26-164612_1920x1080](https://user-images.githubusercontent.com/2467194/47573978-e223d900-d93e-11e8-8b69-ebabb0ac102d.png)

![2018-10-26-164442_1920x1080](https://user-images.githubusercontent.com/2467194/47573827-89544080-d93e-11e8-82f1-49c550ff4a91.png)

---

Thanks!

**Comment by danburkert** [comment]
I believe this has been fixed as part of 0.6.0.  Please feel free to re-open if you are still having issues after updating.
