### ISSUE TITLE
Zero-copy mode

### ISSUE THREAD

**Issue by vorner** [danburkert/prost#134]
Hello

I'm wondering if it was possible to support some kind of zero-copy mode of decoding and encoding (#31 looks slightly related, but not exactly). AFAIK if the protobuf encodes a string or bytes, they are in the buffer vanilla ‒ so they could just be referenced instead of copied out. I haven't done much deep digging, but I think something like this could work:

* Make the `Message` trait somehow lifetime aware (is that even needed? If both the buffer passed to decode and the `Self` contain a lifetime, won't the usual lifetime elision rules apply?).
* Add option to the `prost_build::Config` that prefers using `&str` over `String` and `&[u8]` over `Vec<u8>` (or `Cow` of these).
* Implement `Message` for these types.

Does that make sense? Would that work? Are there any problems I don't see?

**Comment by vorner** [comment]
Huh, I've just discovered #35 too 😇.

Anyway, if it turned out that the lifetime elision actually works, would it be a viable strategy?

**Comment by danburkert** [comment]
I think adding lifetime params and borrowed values would be extremely complex, and not useful  in async contexts, which is an important usecase for `prost`.  #31 outlines an alternate way which doesn't require lifetimes, and remains compatible with the `Buf` trait (`Buf` does _not_ guarantee that buffers are contiguous).  If you want lifetimes, I'd point you towards [quick-protobuf](https://github.com/tafia/quick-protobuf).

**Comment by vorner** [comment]
I don't really insist on lifetimes, they are just probably the most obvious tool to get the job done. I'll try to to look at #31 if it fits the needs, but unlike lifetimes, I don't know if I know how to make that work ‒ but maybe when reading through things, it'll become obvious.

**Comment by danburkert** [comment]
I'm going to close this one out, since zero-copy decoding is available for `bytes` fields, and #392 is tracking support for `string` fields.
