### ISSUE TITLE
Add support for method_attribute()

### ISSUE THREAD

**Issue by snawaz** [danburkert/prost#161]
Currently,  `prost_build::Config` supports `field_attribute()` and `type_attribute()`. Likewise, it'd be really good to have `method_attribute()` so that the generated client can do things like initiating distributed tracing (zipkin):

    #[zipkin_span]
    pub fn client_api(&mut self, foo) -> bar {
    }

And then the users of `prost_build` can implement their own `zipkin_span` or whatever as they want.

_If the idea is good, then I can implement this feature and create the PR. Please review and let me know your thoughts._

**Comment by danburkert** [comment]
@snawaz I think some context is missing.  What is a client?  What generated methods would be useful to trace?  In general the only methods that `prost` generates are field accessors, and encoding/decoding functionality.

**Comment by snawaz** [comment]
> @snawaz I think some context is missing. What is a client? What generated methods would be useful to trace? In general the only methods that `prost` generates are field accessors, and encoding/decoding functionality.

Ahh.. I misread repos. The implementation of the trait `prost_build::ServiceGenerator` isn't provided by `prost` itself. It is rather implemented by [tower-grpc][1] which unfortunately isn't configurable for attribute generations. So this issue should be created for `tower-grpc`. 

Thanks for your quick response. :-)

[1]: https://docs.rs/prost-build/0.3.2/prost_build/trait.ServiceGenerator.html
