### ISSUE TITLE
Shall prost-build-generated source files always include "packed=something" for repeated fields?

### ISSUE THREAD

**Issue by vi** [danburkert/prost#169]
For this message:

```proto
message Msg {
    repeated float eee = 1 [packed=true];
    repeated float qqq = 2;
}
```

prost-build derives the same code. Only after digging a bit I found out that packed=true is default in prost and proto3 has packed by default.

Maybe it shall put `packed="true"` on fields even though it is already true by default?

**Comment by danburkert** [comment]
Not sure I understand, is this a bug report?

**Comment by vi** [comment]
Probably a small minor feature request. Not sure if it's worth it although.

**Comment by danburkert** [comment]
This is intended behavior.
