### ISSUE TITLE
Fail to decode a binary format PerftestData message

### ISSUE THREAD

**Issue by overvenus** [danburkert/prost#17]
Hello,

I did a benchmark about three protobuf crates, [rust-protobuf], [quick-protobuf] and this, prost. :-)

------------------

I found an unexpected error when decoding a binary format message, PerftestData.

```
Error { repr: Custom(Custom { kind: InvalidData, error: StringError("invalid zero tag value") }) }
```

Snippet:

```rust
let mut is = File::open(&Path::new("perftest_data.pbbin")).unwrap();
let mut data = Vec::new();
is.read_to_end(&mut data).unwrap();
let mut bin = bytes::Bytes::from(data).into_buf();

// FIXME: Error { repr: Custom(Custom { kind: InvalidData, error: StringError("invalid zero tag value") }) }
let test_data_prost = perftest_data_prost::PerftestData::decode_length_delimited(&mut bin).unwrap();
```
See more at https://github.com/overvenus/quick-protobuf/blob/aeef8af0467eb15983f34d5ac1eab17539b19815/benches/rust-protobuf/perftest.rs#L354-L359

Is it a bug or am I missing something?

Thank you!

[rust-protobuf]: https://github.com/stepancheg/rust-protobuf

[quick-protobuf]: https://github.com/tafia/quick-protobuf

**Comment by danburkert** [comment]
Hi @overvenus, it looks like you're calling `decode_length_delimited`, but the data isn't actually length delimited.  Use `Message::decode` instead.

**Comment by danburkert** [comment]
I'm able to get it passing with this diff:

```

**Comment by overvenus** [comment]
Oh, got it. Thank you! :grinning:

**Comment by danburkert** [comment]
No problem!
