### ISSUE TITLE
Deriving custom traits?

### ISSUE THREAD

**Issue by JoeHowarth** [danburkert/prost#175]
Is it possible to derive extra traits? Such as:
``` rust
#[derive(Add)]
struct Foo {
    x: u8
}
```

**Comment by adeschamps** [comment]
Yes, I believe you're looking for [`Config::type_attribute()`](https://docs.rs/prost-build/0.5.0/prost_build/struct.Config.html#method.type_attribute):

```rust
let mut config = prost_build::Config::new();
config.type_attribute(".", "#[derive(Add)]");
config.compile_protos(&["src/items.proto"], &["src/"])?;
```

**Comment by JoeHowarth** [comment]
Awesome! Didn't see that, thanks
