### ISSUE TITLE
rustc "expected identifier" at ::prost::Oneof

### ISSUE THREAD

**Issue by pedrosland** [danburkert/prost#178]
I have a proto file from googleapis that I'd like to use from rust. protoc-build generates a source file but the rust compiler doesn't like it.

It isn't clear to me why it doesn't like this Oneof since there is an earlier occurrence that seems ok.

[Sample repo](https://github.com/pedrosland/prost-test). The prost-build generated file is in the repo root at `google.datastore.v1.rs`.

Output from the rust compiler:
```
error: expected identifier, found `::`
   --> proc-test/target/debug/build/proc-test-05d4b410896dfabd/out/google.datastore.v1.rs:121:32
    |
121 |     #[derive(Clone, PartialEq, ::prost::Oneof)]
    |                                ^^^^^^^^^^^^^^
    |                                |
    |                                expected identifier
    |                                while parsing this match expression

error: proc-macro derive produced unparseable tokens
   --> proc-test/target/debug/build/proc-test-05d4b410896dfabd/out/google.datastore.v1.rs:121:32
    |
121 |     #[derive(Clone, PartialEq, ::prost::Oneof)]
    |                                ^^^^^^^^^^^^^^

error: aborting due to 2 previous errors
```
Generated source snippet:
```
/// A message that can hold any of the supported value types and associated
/// metadata.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Value {
    /// The `meaning` field should only be populated for backwards compatibility.
    #[prost(int32, tag="14")]
    pub meaning: i32,
    /// If the value should be excluded from all indexes including those defined
    /// explicitly.
    #[prost(bool, tag="19")]
    pub exclude_from_indexes: bool,
    /// Must have a value set.
    #[prost(oneof="value::ValueType", tags="11, 1, 2, 3, 10, 5, 17, 18, 8, 6, 9")]
    pub value_type: ::std::option::Option<value::ValueType>,
}
pub mod value {
    /// Must have a value set.
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ValueType {
        /// A null value.
        #[prost(enumeration="::prost_types::NullValue", tag="11")]
        NullValue(i32),
```

I have tried on nightly, stable 2015 and stable 2018.
I have tried using the latest protoc (libprotoc 3.7.1) and includes by specifying the environment variables:
```
PROTOC=protoc PROTOC_INCLUDE=protobuf-3.7.1/include cargo build
```
Unfortunately none of the above work for me.
```
rustc --version
rustc 1.34.1 (fc50f328b 2019-04-24)
```

**Comment by danburkert** [comment]
hey @pedrosland, thanks for the detailed report and repro repo!  There are a couple of things going on here; one is a bug in `prost` which I'm addressing in #185, and the other is that the `include!` statements aren't quite right in that project, check out [this](https://github.com/danburkert/prost-test/commit/ff343f33b17689784d7275793b203dd3115b2fa1) commit to see a fix.

**Comment by danburkert** [comment]
Fix has been merged.

**Comment by pedrosland** [comment]
That's brilliant @danburkert. Thanks for fixing #185 and my repo too. Your commit makes sense to me.

**Comment by JanYunkai** [comment]
redeploy?
