### ISSUE TITLE
Replace values of scalar fields instead of concatenating on merge

### ISSUE THREAD

**Issue by mzabaluev** [danburkert/prost#195]
Google's [guide](https://developers.google.com/protocol-buffers/docs/encoding#optional) on protobuf encoding says this:

> Normally, an encoded message would never have more than one instance of a non-repeated field. However, parsers are expected to handle the case in which they do. For numeric types and strings, if the same field appears multiple times, the parser accepts the _last_ value it sees.

As currently implemented by functions `bytes::merge` and `string::merge` in `encoding.rs`, the values are concatenated.

**Comment by danburkert** [comment]
This should be fixed as of 0.6.0.  It was revealed while updating to the 3.11 upstream conformance tests that prost wasn't handling this properly.
