### ISSUE TITLE
Define custom code generation

### ISSUE THREAD

**Issue by hunterlxt** [danburkert/prost#199]
I'm new to learn prost, some way to define custom code generation by myself. Because when I using nightly rust, I encountered the following warning

![image](https://user-images.githubusercontent.com/18193301/59975366-1ba20680-95ea-11e9-86e3-1476b068018f.png)

**Comment by danburkert** [comment]
`prost` doesn't generate an `as_any` method, so it's unlikely to be an issue with `prost`.  From the path it may be due to a grpc library?

**Comment by hunterlxt** [comment]
Yeah, this is related with `protobuf-build`, thanks.
