### ISSUE TITLE
Manually Specify Package?

### ISSUE THREAD

**Issue by naftulikay** [danburkert/prost#208]
I'm attempting to create data mappings for Envoy's ProtoBuf API while also attempting to implement Serde's JSON de/serialization for these types. I am going to attempt to use `proto-build` to build the initial definitions, but I will most likely have to edit the generated source files to support Serde.

Is there a way that I can add a `package` tag on each type to manually specify its ProtoBuf package without necessarily having to obey the package structure?

**Comment by danburkert** [comment]
I'm not sure I fully understand the question, but one of the core features of `prost` is that it maps the .proto package hierarchy into the corresponding Rust module hierarchy.  There's no way to turn off this mapping.  Note that it is _is_ possible to 'mount' a module hierarchy generated by `prost` into any Rust module, for an example see how the [`packages`](https://github.com/danburkert/prost/blob/master/tests/src/packages/root.proto) PB package is mounted into the [`tests::packages`](https://github.com/danburkert/prost/blob/master/tests/src/packages/mod.rs#L3) module.  In effect you can move around the packages as you see fit, as long as the relative path between `prost` generated packages stays the same.

As far as Serde, you may want to take advantage of the [`type_attributes`](https://docs.rs/prost-build/0.5.0/prost_build/struct.Config.html#method.type_attribute) configuration option.

**Comment by naftulikay** [comment]
> In effect you can move around the packages as you see fit, as long as the relative path between prost generated packages stays the same.

Oh great! I'm not as familiar with ProtoBuf as I'd like, I assumed that there was some kind of hardcoding being done with package names and that there wouldn't be any flexibility around their location. If I'm just able to move everything into `envoyproxy::data::*`, that would be ideal to separate it from other things in the crate.

**Comment by danburkert** [comment]
Going to close this out, please feel free to re-open if there's something more that needs to be done.
