### ISSUE TITLE
Add accessor methods to get Option<&T>

### ISSUE THREAD

**Issue by fujiapple852** [danburkert/prost#210]
Following [this](https://www.reddit.com/r/rust/comments/cmzmbf/ergonomic_decomposition_of_structs_with_nested/) discussion I would like to propose adding a feature to the PROST code generator to generate accessor methods for (at least) `Option<T>` fields such that client code can obtain an `Option<&T>` directly without having to do an explicit `as_ref()` for each.  This would make working with PROST generated code more ergonomic for structs with nested optional fields.

@danburkert if you are supportive of the idea I would be willing to work on this and submit a PR.

**Comment by danburkert** [comment]
@fujiapple852 is this for proto2 optional fields?  Are you aware that `prost` already generates accessors which return the value, if present, otherwise the default value?  That's typically what you want to be using, except in the rare cases where you need to handle unset values as something other than the default.

For instance, see this [proto2 type](https://github.com/protocolbuffers/protobuf/blob/da5d02bced1fa3d543d026e3f2a03d3259500ed7/src/google/protobuf/descriptor.proto#L509-L600) and the [corresponding generated accessors](https://docs.rs/prost-types/0.5.0/prost_types/struct.FieldOptions.html#method.ctype).

**Comment by fujiapple852** [comment]
@danburkert my description of the feature suggestion above was not as clear as it should have been, apologies for that, let me try to clarify.

Suppose we have the following proto definition (assuming `proto3` here though I imagine it would be the same for a `optional` field in `proto2`):

````
syntax = "proto3";
package test;
message Foo {
  Bar bar = 1;
}
message Bar {
  Baz baz = 1;
}
message Baz {
  string val = 1;
}
````
The `prost` code generator will generate the following, sensibly using `Option<T>` to represent each nested message given the optional semantics for embedded message fields in `proto3`:
````
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Foo {
    #[prost(message, optional, tag = "1")]
    pub bar: ::std::option::Option<Bar>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Bar {
    #[prost(message, optional, tag = "1")]
    pub baz: ::std::option::Option<Baz>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Baz {
    #[prost(string, tag = "1")]
    pub val: std::string::String,
}
````
The thread I linked above discusses various options for ergonomically traversing such structures which (ignoring more elaborate techniques such as visitors patterns) boils down to three options; pattern destructing, combinators & the `try_block` (nightly only but can be emulated to an extent on stable using a closure):

    // option 1: match
    let val1 = match foo.as_ref() {
        Some(Foo {
            bar: Some(Bar {
                baz: Some(Baz { val }),
            }),
        }) => Some(val.as_str()),
        _ => None,
    };
    dbg!(val1);

    // option 2: combinators
    let val2 = foo.as_ref()
        .and_then(|f| f.bar.as_ref())
        .and_then(|b| b.baz.as_ref())
        .map(|z| z.val.as_str());
    dbg!(val2);

    // option 3: poor man's try_block on stable
    let val3 = (|| Some(foo.as_ref()?.bar.as_ref()?.baz.as_ref()?.val.as_str()))();
    dbg!(val3);

As was noted by user `asymmetrikon` in the thread:

> Often it's nice to have structs that have `Option<T>` members have getter functions that return `Option<&T>` so you can avoid all the `as_refs()`

The suggestion therefore is to enhance the `prost` code generator to emit accessor methods that return `Option<&T>` for fields such as `Foo::bar` and `Bar::baz` above:

````
impl Foo {
    pub fn bar(&self) -> Option<&Bar> {
        self.bar.as_ref()
    }
}

impl Bar {
    pub fn baz(&self) -> Option<&Baz> {
        self.baz.as_ref()
    }
}
````

With this option's 2 & 3 above could become a little more ergonomic (an accessor for `Baz::val` which returns an `&str` also added for good measure):

    // option 2 simplified
    let val4 = foo.as_ref()
        .and_then(Foo::bar)
        .and_then(Bar::baz)
        .map(Baz::val);
    dbg!(val4);

    // option 3 simplified
    let val5 = (|| Some(foo.as_ref()?.bar()?.baz()?.val()))();
    dbg!(val5);

So whilst this feature does not enable any functionality not supported by `prost` today, it should make working with the generated code slightly more ergonomic.

**Comment by danburkert** [comment]
@fujiapple852 while I'm sympathetic to the issue, this isn't specific to protobuf or really even `prost`, so I don't want to take on generating extra methods for every struct field.  If it's really causing pain, I recommend finding or creating your own derive macro to generate the methods, then you can configure `prost` to add that derive annotation to the generated struct types.

**Comment by fujiapple852** [comment]
Understood @danburkert, I think the rationale makes sense.  The custom derive approach sounds sensible, I'll explore that option and drop a comment here with what I find.  This issue can be closed.
