### ISSUE TITLE
Update proc-macro2, syn & quote to 1.0

### ISSUE THREAD

**Issue by hobofan** [danburkert/prost#218]
The three proc macro libraries were recently released as 1.0, so it would be great to have a updated version of prost with those for less duplicate dependencies.

**Comment by repi** [comment]
Agreed, now after `failure` was upgraded this is our only dependency that brings in the old `syn` pre-1.0 version. So would definitely be nice to have `prost-derive` upgraded

**Comment by danburkert** [comment]
Released as part of 0.6.0.
