### ISSUE TITLE
protobuf build.rs sometimes fails

### ISSUE THREAD

**Issue by cbeck88** [danburkert/prost#222]
I am finding that when testing `prost`, about half the time, the `protobuf` build fails, with the following, inside the `protobuf` make process:

```
ar: `u' modifier ignored since `D' is the default (see `U')
In file included from binary_json_conformance_suite.h:34,
                 from binary_json_conformance_suite.cc:31:
conformance_test.h:49:10: fatal error: conformance.pb.h: No such file or directory
 #include "conformance.pb.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:908: conformance_test_runner-binary_json_conformance_suite.o] Error 1
make: *** Waiting for unfinished jobs....
thread 'main' panicked at 'failed to make conformance', protobuf/build.rs:182:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I find that it always succeeds if I do this, in the `protobuf/build.rs`:

```
        let rc = Command::new("make")
            .arg("-j")
            .arg("1") // Note: 1 instead of NUM_JOBS to work around bugs in makefile
            .arg("install")
            .current_dir(src_dir.join("conformance"))
            .status()
            .expect("failed to execute make conformance");
        assert!(rc.success(), "failed to make conformance");
```

Would you be interested in a patch like this?

**Comment by danburkert** [comment]
Interesting, can you repro this just with protobuf?  I don't want to limit parallelism on the build since building the conformance tests is already so slow, it would make CI even worse.  If you can repro just on the protobuf repo you can file a bug with them.  It looks somewhat similar to this workaround I had to introduce: https://github.com/danburkert/prost/pull/191/files

**Comment by danburkert** [comment]
Also might be worth seeing if it's an issue with the latest protobuf; we can always bump the bundled protobuf version in `prost`.

**Comment by cbeck88** [comment]
sounds good, will write back

**Comment by danburkert** [comment]
I switched `prost` over to using CMake when building protobuf, so hopefully this is no longer an issue.  Please feel free to re-open if it's still failing on latest `prost` master.
