### ISSUE TITLE
How can i generate non optional field ?

### ISSUE THREAD

**Issue by mineralres** [danburkert/prost#223]
Here is my proto3 definition:

`syntax = "proto3";
message A {
   B b = 1;
}`

the generated rust code:
`pub struct A {
   pub b: ::std::option::Option<B>
}`

can i remove the std::option::Option?
according to the readme [field-modifiers](https://github.com/danburkert/prost#field-modifiers) ,there is a "default" modifier in proto3, which i can't find it in [language guide(proto3)](https://developers.google.com/protocol-buffers/docs/proto3)

**Comment by JohnDoneth** [comment]
I believe that might be a typo and that the "default" is `Option<T>` and not `T`. Required and optional were removed from .proto3. It is no longer possible to have a required (Non-`Option`) field in proto3.

Source: https://stackoverflow.com/a/42634681

**Comment by Timmmm** [comment]
You can't. See #97

However it would nice to have an option to make Prost use default values for fields instead of `None`.

**Comment by danburkert** [comment]
It's not possible to change when fields are wrapped in `Option`, other than through the field modifiers in the `.proto`.  Note that in many cases field accessor methods are generated which return the unwrapped value or the default.
