### ISSUE TITLE
Code completion

### ISSUE THREAD

**Issue by Timmmm** [danburkert/prost#229]
Is there any way to get code completion to work with Prost via RLS or rust-analyzer.

It basically doesn't work because the source is included like this:

```
pub mod plugin {
	include!(concat!(env!("OUT_DIR"), "/file.rs"));
}
```

And RLS doesn't know what `OUT_DIR` is (I doubt it supports all that macro complexity anyway to be honest).

It would be nice if there were a way to fix this.

Edit: There was [an existing issue for this in `rust-analyzer`](https://github.com/rust-analyzer/rust-analyzer/issues/1964), added 4 days ago coincidentally.

**Comment by bryandmc** [comment]
If we implement a proc-macro for the stuff that is currently done in build.rs -- it might work.. I personally use intellij-rust plugin (with clion, for debugger support) and it also can't figure this out. It's actually got good support for a lot of macros and if we moved the build.rs stuff into a macro it could potentially understand it.

I've though about creating this sorta shim if the creator of PROST is not interested in doing it in this crate..

**Comment by Timmmm** [comment]
Code completion works nicely with #231 and outputting to the source directory. Then I can just include it normally.

**Comment by Timmmm** [comment]
Anyway I think this can be closed because it's really rust-analyzer and IntelliJ's problem.
