### ISSUE TITLE
Only write files when the contents have changed

### ISSUE THREAD

**Issue by Timmmm** [danburkert/prost#231]
As a workaround to code completion not working (#229), and because I've decided it is a good idea anyway, I changed my `build.rs` to output the generated code to the source directory.

Unfortunately it completely breaks rust-analyzer which watches the code for changes, then runs `build.rs` and gets stuck in a loop.

Probably should be fixed there, but I think a simple and worthwhile fix would be for prost-build to only write files if their contents have changed. I've used this technique in a CMake based project and it works very well.

Might fix #139 too, who knows.

**Comment by BenChand** [comment]
@Timmmm Would you happen to have an example of changing your `build.rs` to output the generated code to the source directory? I'd like to do something similar

**Comment by Timmmm** [comment]
I'm afraid not, we switch to using a home grown RPC system based on bincode instead of Protobuf a while ago. Sorry!
