### ISSUE TITLE
improve deny(missing_docs) compatibility

### ISSUE THREAD

**Issue by dunmatt** [danburkert/prost#233]
Trying the example from https://docs.rs/prost-build/0.5.0/prost_build/ with #![deny(missing_docs)] on has some issues:

1)  The comment for the `Shirt` message doesn't get applied to the generated `shirt` module.

2) The `::prost::Message` proc macro seems to generate at least one method, and that method doesn't have a doc string.

Ideally I'd rather not make an `allow(missing_docs)` exception because I like the idea of forcing my users to document their messages.  Would you be open to a PR that fixes these things?

**Comment by danburkert** [comment]
Should be fixed as of #323, please feel free to re-open if the issue remains.
