### ISSUE TITLE
Compiling prost-derive on unknown x86_64 musl

### ISSUE THREAD

**Issue by ChristopherRabotin** [danburkert/prost#236]
I have a source file in C which calls a Rust dylib and performs some computation. To build, I need to pass the `-crt-static` flag. `cargo` reports an error saying that it cannot compile `prost-derive` is a [dependency of `nyx-space`](https://gitlab.com/chrisrabotin/nyx/blob/master/Cargo.toml#L19), which is a dependency of the dylib library (`orbitprop`).

![prostderive](https://user-images.githubusercontent.com/4823784/67886148-94701c80-fb0e-11e9-91ac-a41dbf6b05bf.png)

Any idea how I can fix this?

Thanks

**Comment by danburkert** [comment]
I don't know exactly what's going on here, but I don't think it's particular to `prost`.  Please feel free to re-open if there's something actionable `prost` can improve here.
