### ISSUE TITLE
Option<T> only generated for sub-message fields

### ISSUE THREAD

**Issue by jthomas-geotab** [danburkert/prost#238]
For the following .proto file:

    syntax = "proto3";

    package company.product;

    message Foo {
        Bar bar = 1;
        int32 i = 2;
        string str = 3;
    }

    message Bar {
    }

the generated .rs file:

    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Foo {
        #[prost(message, optional, tag="1")]
        pub bar: ::std::option::Option<Bar>,
        #[prost(int32, tag="2")]
        pub i: i32,
        #[prost(string, tag="3")]
        pub str: std::string::String,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Bar {
    }

only has Option&lt;T&gt;'s for bar, whereas it should have them for all fields, as all fields are optional in proto3.

**Comment by danburkert** [comment]
This is working as intended.  Scalar proto3 fields are optional during deserialization, if they are missing, the default value is filled in.  This is how, for instance, c++ works.

**Comment by jthomas-geotab** [comment]
Yes, you are right, I was mistaken in my understanding of optional in proto3, it is not the same as optional in proto2.
