### ISSUE TITLE
Implement `From<OneOfVariant> for message_with_oneof::OneOfName`

### ISSUE THREAD

**Issue by Sushisource** [danburkert/prost#243]
I saw the related item https://github.com/danburkert/prost/issues/42 -- I agree changing the representation or having two is unneeded.

However, I think ergonomics could be dramatically improved by generating implementations like the one in the title.

Does that make sense to you? If I can find the time, it'd be something I'd be happy to contribute if so.

For now, I've just been writing these by hand.

For more clarity on what I mean:

```proto
message ContainerMsg {
    oneof container_field {
        A a = 10;
        B b = 11;
    }
}

message A { ... }
message B { ... }
```

Would include these generated impls:

```rust
impl From<A> for container_msg::ContainerField {
    fn from(x: A) -> Self {
        container_msg::ContainerField::A(x)
    }
}

impl From<B> for transaction_update::Status {
    fn from(x: B) -> Self {
        container_msg::ContainerField::B(x)
    }
}
```

**Comment by danburkert** [comment]
This isn't possible because `oneof`s can and often do have multiple variants with the same type.

**Comment by Sushisource** [comment]
@danburkert Ah, yeah that makes perfect sense. Would you be open to adding the `From` impl in the event that they don't? I have no such cases in my proto defs, and being able to call `Variant.into()` rather than `fieldname::Variant(Variant)` would be pretty nice.

I'd be happy to contribute it if you're open to it.

**Comment by Sushisource** [comment]
Nevermind, for anyone who comes across this while searching, this is easily accomplished now by using https://docs.rs/prost-build/0.7.0/prost_build/struct.Config.html#method.type_attribute to add `derive(::derive_more::From)`
