### ISSUE TITLE
compile_protos for multi-lang project

### ISSUE THREAD

**Issue by ameets** [danburkert/prost#25]
My project is structured such that the .proto files live in a different directory from the rust code and build.rs script. The main driver for this is to allow both the go and rust codebases to share a common set of protos across the project. 

```project
|—>go
|	|—>file.go
|
|—>proto
|	|—>my.proto
|
|—>rust
	|—>Cargo.toml
	|—>build.rs
	|—>src
		|—>lib.rs
```

I haven't figured out the right way to specify the proto path to `compile_protos` and get the following error when providing the absolute path. What is the correct way to do this? 

_File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it\'s harder than you think).\n") }) }', src/libcore/result.rs:906:4

prost_build::compile_protos in build.rs_

**Comment by danburkert** [comment]
What are you passing to `compile_protos`?  Note that you have to pass the protoc path, just like you would when calling `protoc` from the command line, it should probably look something like

```rust
    prost_build::compile_protos(&["../proto/my.proto"]),
                                &["../proto"]).unwrap();

**Comment by ameets** [comment]
Ahh got it. It's working when I use the correct protoc path 👍
