### ISSUE TITLE
Consider dropping dependency on `failure` in prost-derive

### ISSUE THREAD

**Issue by nagisa** [danburkert/prost#258]
prost-derive uses `failure` very lightly and the crate has fallen out of favour in the community. Consider moving to `anyhow` (that crate has no dependencies!) or directly to the standard error trait.

**Comment by danburkert** [comment]
Sounds good to me, `prost-derive` definitely doesn't need heavy weight error handling.   I'd be fine with just `Result<_, String>` to be honest.  I'm not going to work on this in the short term, so I'd encourage a PR.
