### ISSUE TITLE
Bug: built program fails to build with prost 0.6.0

### ISSUE THREAD

**Issue by Nokel81** [danburkert/prost#265]
Hello, I have the following build script snippet:

```rust
 tonic_build::configure()
        .build_server(false)
        .compile(
            &[&action],
            &[&include_dir, &grpc_gateway, &googleapis],
        )
        .expect("tonic");
```

I am currently using `0.5.0` (on both `prost` and `prost-types`) but since `v0.6.0` just came out, I wanted to see if I could upgrade. But when I do, I keep getting a whole bunch of the following errors:

```
self.inner.unary(request.into_request(), path, codec).await
           ^^^^^
the trait `prost::message::Message` is not implemented for `com::nokel::action::v1::RenderClusterJoinManifestResponse
```

**Comment by danburkert** [comment]
Hi, this is probably because one of your dependencies (likely `tonic`) is pointing to the 0.5 version of `prost`.  You'll need to get or wait for a version of `tonic` that depends on the new prost version.  I believe the tonic team is working on that actively.

**Comment by LucioFranco** [comment]
should be out very soon!
