### ISSUE TITLE
prost-build define order in type attributes

### ISSUE THREAD

**Issue by raz-adroll** [danburkert/prost#273]
Hi,

I'm using prost-build with a custom type attribute,
`prost_build.type_attribute(".", "#[pyclass]");`
but when I run it, I get:
`error: macro attributes must be placed before #[derive]`
and when I see the output I get:
```
#[derive(Clone, PartialEq, ::prost::Message)]
#[pyclass]
pub struct ...
```
Is there a way to establish the order of the attributes?

Thanks!

**Comment by danburkert** [comment]
Interesting, I wasn't aware of this requirement.  There's currently no way to define the ordering.  It sounds like `prost-build` should be sorting the type attributes, with `derive`s last, then applying them above the built-in derives.  This is where it happens: https://github.com/danburkert/prost/blob/v0.6.1/prost-build/src/code_generator.rs#L255-L265
