### ISSUE TITLE
Prost build fails using CC arm-linux-gnueabihf-gcc for arch armv7-a

### ISSUE THREAD

**Issue by amrx101** [danburkert/prost#274]
When trying to cross compile Prost for armv7-a using arm-linux-gnueabihf-gcc, the build fails with error

    arm-linux-gnueabihf-gcc: error: unrecognized command line option ‘-m64’

Rust version: 1.40.0

**Comment by danburkert** [comment]
@amrx101 please provide more details about the error, the failing command, etc.  As is, this is not an actionable bug report.  Feel free to re-open with more information.
