### ISSUE TITLE
Prost build doesnt generate Rust files.

### ISSUE THREAD

**Issue by amrx101** [danburkert/prost#275]
If you follow along the  prost-build documentation, it doesnt generate .rs files.

**Comment by amrx101** [comment]
In main.rs

    pub mod items {
    include!(concat!(env!("OUT_DIR"), "/helloworld.rs"));
    }

    fn main() {
         println!("Hello, world!");
    }


build.rs

fn main() {
    prost_build::compile_protos(&["src/proto/helloworld.proto"],
                                &["src/"]).unwrap();
}

**Comment by danburkert** [comment]
Hi @amrx101, this is not an actionable issue without details such as the contents of the `.proto` file, the failing command, and the failure output.  Please provide these details and re-open.
