### ISSUE TITLE
prost-build doesn't allow build.rs to override protoc

### ISSUE THREAD

**Issue by Baughn** [danburkert/prost#305]
As I'm running in an environment where the protoc download doesn't work (NixOS), I'd like to use the protoc in my PATH by default.

This should be relatively straightforward:
```rust
use std::env;

fn main() {
    if let Err(_) = env::var("PROTOC") {
        let protoc = which::which("protoc").expect("Searching for protoc");
        println!("Using {}", protoc.display());
        env::set_var("PROTOC", protoc);
    }

    prost_build::compile_protos(&["src/logging.proto"], &["src"]).expect("Protobuf compilation");
}
```

However, because lib.rs uses `env!` to embed the value of PROTOC at build time, there's no way to override it from inside the build script.

Can I request you use `std::env::var("PROTOC")` instead?

**Comment by gabrielrussoc** [comment]
I prepared #307 for this

**Comment by kuznero** [comment]
Did anyone find a way to workaround this issue in NixOS? Building prost from custom PR-branch that uses path to PROC resolved in runtime?

**Comment by gabrielrussoc** [comment]
@kuznero yes, we are using the branch from #307 while we wait for a permanent solution

**Comment by danburkert** [comment]
I believe this should be fixed on master via #307.

**Comment by kuznero** [comment]
@danburkert is there a plan to make a release to crates.io (`prost-build = "0.6.2"?`)

**Comment by Baughn** [comment]
+1

I can't reopen this, but I also can't use Prost until there's a release with this fixed.
