### ISSUE TITLE
Case bug in proc macro generation

### ISSUE THREAD

**Issue by mcd1992** [danburkert/prost#310]
Using a proto file like so, with a default in it.
```
enum ERemoteClientBroadcastMsg {
	k_ERemoteClientBroadcastMsgDiscovery = 0;
}
message CMsgRemoteClientBroadcastHeader {
	optional ERemoteClientBroadcastMsg msg_type = 2 [default = k_ERemoteClientBroadcastMsgDiscovery];
}
```

Generates rust code like:
```
pub struct CMsgRemoteClientBroadcastHeader {
    #[prost(enumeration="ERemoteClientBroadcastMsg", optional, tag="2", default="KeRemoteClientBroadcastMsgDiscovery")]
    pub msg_type: ::std::option::Option<i32>,
}
```

Which has a case error in default specified in the proc macro. It should be generating the default to `KERemoteClientBroadcastMsgDiscovery`. This is with prost 0.6.1

**Comment by danburkert** [comment]
Thanks for the thorough report.  I've reproduced this, and I'm working on a fix.
