### ISSUE TITLE
Protoc binary downloaded during build is not statically linked

### ISSUE THREAD

**Issue by kuznero** [danburkert/prost#316]
Protoc binary that is downloaded is used in an ad-hoc manner on Linux systems might require preliminary `patchelf --set-interpreter` invoked on this binary. In order to avoid that, it makes sense to:

- either download fully statically linked Protoc binary (if it exists)
- or allow to specify path to it in runtime as appose to the current approach

Existing PR #307 might have a fix for it.

**Comment by danburkert** [comment]
I'm happy with #307, so I'll be merging that soon.  I'll also be merging #283 which kind of goes hand in hand.

As far as a statically linked protoc, I'd really like to have that, but more importantly I want to ship the upstream compiled artifacts, to have at least some chain of authenticity.  Perhaps someone could work with upstream to have them switch over to static builds (I don't have the bandwidth, unfortunately).

**Comment by danburkert** [comment]
Both those PRs have been merged, so I'm going to close this.  If there's still more left to do please feel free to reopen.

**Comment by kuznero** [comment]
Super! Thanks!
