### ISSUE TITLE
Please release v0.6.2

### ISSUE THREAD

**Issue by kuznero** [danburkert/prost#329]

**Comment by danburkert** [comment]
The next version will be `0.7.0` or `0.7.0-rc1`, there have been a bunch of breaking changes that have landed recently.  None are very impactful, but technically breaking nonetheless.

**Comment by benma** [comment]
Doesn't breaking change mean a major version bump?

Anyway, I am also interested in a release, especially since no_std seems to be supported now.

**Comment by benma** [comment]
Is there an ETA for this? I am really looking forward to using prost, but I would need a new release for that.

Alternatively, if you think `master` is in good shape in general, I could also use that.

**Comment by joseph-wakeling-frequenz** [comment]
@benma 
> Doesn't breaking change mean a major version bump?

Strictly speaking, semver allows breaking changes in any v0.x.y release: see https://semver.org/#spec-item-4 and also the FAQ that follows.

A more useful pattern (which I assume prost is following), sometimes known as the `0.MAJOR.PATCH` semver extension, is to allow minor v0.x release bumps to include breaking changes, but not patch releases, i.e. v0.x.y => v0.(x+1).0 can contain a breaking change, but not v0.x.y => v0.x.(y+1).

**Comment by joseph-wakeling-frequenz** [comment]
Anyway, @danburkert if you have a moment, I would also really appreciate either the v0.7.0 release or at least an ETA for it, as current master branch already contains very useful fixes.

Are there any particular blockers or things that you are looking to finalize?  Just on the off-chance that some of us in the user community might be able to help out?

**Comment by Veetaha** [comment]
@danburkert, I'd suggest giving some contributor the rights to push to the repo and release the package if you feel that you don't have enough time/motivation for maintaining the project?

**Comment by danburkert** [comment]
https://github.com/danburkert/prost/pull/326

**Comment by benma** [comment]
Looks one of them is merged, and the other seems close? :pray:

**Comment by kinosang** [comment]
any update here?

**Comment by x1ddos** [comment]
+1 a release any time now would be very much appreciated.

**Comment by kuznero** [comment]
Having this in your `Cargo.toml` seems to help a bit:

```
[patch.crates-io]
prost = { git = "https://github.com/danburkert/prost" }

[dependencies]
prost = { git = "https://github.com/danburkert/prost" }
tonic = { version = "0.3", features = ["tls"] }
tokio = { version = "0.2", features = ["stream", "macros"] }
futures = "0.3"

[build-dependencies]
tonic-build = { version = "0.3" }
```

This will essentially patch `prost` from under the `tonic`.

**Comment by benma** [comment]
Bump :pray:

**Comment by danburkert** [comment]
v0.7.0 is released.  Thanks all.

**Comment by wchargin** [comment]
@danburkert thanks very much! :-)

**Comment by wchargin** [comment]
Since Tonic 0.4.0 is now out, too, I just upgraded my proto-heavy
application to Prost 0.7.0 and saw a 10% end-to-end performance
improvement with no code change on my end. Much appreciated; thanks!
