### ISSUE TITLE
Can't use decode_length_delimited from a tokio Decoder implementation.

### ISSUE THREAD

**Issue by megmacattack** [danburkert/prost#33]
The signature for tokio's decode function in its codec library is:

```rust
fn decode(&mut self, buf: &mut BytesMut)
```

This is the error I encounter trying to use it specifically:

```
   |
57 |         match T::decode_length_delimited(buf) {
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `bytes::Buf` is not implemented for `bytes::BytesMut`
   |
   = note: required because of the requirements on the impl of `bytes::Buf` for `&mut bytes::BytesMut`
   = note: required because of the requirements on the impl of `bytes::IntoBuf` for `&mut bytes::BytesMut`
   = note: required by `prost::Message::decode_length_delimited`
```

But `decode_length_delimited` expects an IntoBuf/Buf as its input. There does not appear to be a way to translate a BytesMut into something with the Buf trait short of copying it into a new buffer? (since the buffer is passed in borrowed you can't `freeze()` it)

**Comment by danburkert** [comment]
I think you may be looking for [`BytesMut::freeze()`](https://docs.rs/bytes/0.4.5/bytes/struct.BytesMut.html#method.freeze).
