### ISSUE TITLE
#[derive(Default) for generated code.

### ISSUE THREAD

**Issue by brpatel12** [danburkert/prost#339]
Would it be possible to change the generated code to:
```
#[derive(Clone, Default, PartialEq, ::prost::Message)]
pub struct <prost::Message> { ... }
```

I am new to rust but I think this will allow for initializing proto messages without having to define all of its guts.

**Comment by nhynes** [comment]
Have you tried using [prost_build::Config::type_attribute](https://docs.rs/prost-build/0.6.1/prost_build/struct.Config.html#method.type_attribute)?

**Comment by brpatel12** [comment]
Thanks!!!
