### ISSUE TITLE
Compile errors for enumeration referencing `super`

### ISSUE THREAD

**Issue by ameets** [danburkert/prost#34]
I was trying to structure my protos directory and ran into a compile error that I haven't been able to fix. I've extended your snazzy shirt example with the below directory structure and sizes.proto and items.proto files respectively:
```
protos
    |-items
           |-items.proto
    | -sizes
           |-sizes.proto
```

```sizes.proto
syntax = "proto3";

package snazzy.size;

enum Size {
    SMALL = 0;
    MEDIUM = 1;
    LARGE = 2;
}
```

```items.proto
syntax = "proto3";

package snazzy.items;

import "sizes/sizes.proto";

message Shirt {
	string color = 1;
	snazzy.size.Size size = 2;
}
```
The rust compiler cannot find the enumeration via `super` reference: 
`#[derive(Clone, Debug, PartialEq, Message)]
                                     ^^^^^^^ Could not find size in super`
```snazzt.items.rs
#[derive(Clone, Debug, PartialEq, Message)]
pub struct Shirt {
    #[prost(string, tag="1")]
    pub color: String,
    #[prost(enumeration="super::size::Size", tag="2")]
    pub size: i32,
}
```
Any thoughts on how I can work around this or if I'm missing something in the setup?

**Comment by danburkert** [comment]
What does your `.rs` file containing the `include!` calls look like?  I think in this case the `include!` calls need to be in module trees which mimic the proto packages.  You can see an example of this here: https://github.com/danburkert/prost/blob/master/tests/src/packages/mod.rs#L5-L14.

**Comment by ameets** [comment]
Got it - thanks for pointing me to the test examples. I ended up needing to restructure the proto packages and nest the module trees similar to your example.

Thanks!

**Comment by ameets** [comment]
This latest [fix](https://github.com/danburkert/prost/commit/ee771a2b7568af25054c54d882e993b3ebba3512) fixed the compile errors I previously reported. 

Thanks!

**Comment by danburkert** [comment]
Ah, sorry about that.  I should have put two and two together that you were likely hitting that.  I'm planning on doing a 0.2.1 soon in order to get the fix out, because I think it's likely to be a common issue (I ran into it independently).

**Comment by danburkert** [comment]
`0.2.1` has been published, and includes the fix.  Thanks for the report!
