### ISSUE TITLE
Strings that are not valid UTF-8 can be encoded but error on decoding

### ISSUE THREAD

**Issue by wagenet** [danburkert/prost#342]
It seems that encoding should raise an error if decoding will.

**Comment by danburkert** [comment]
Can you give an example?  I don't see how it'd be possible to encode a not-valid utf-8 string without using an unsound use of `unsafe`.

**Comment by wagenet** [comment]
@danburkert the case where I ran into it was indeed from an unsafe use. Some very old code that I didn't write had `str::from_utf8_unchecked`. This eventually got serialized into a protobuf with Prost. I was surprised that it serialized successfully but could not deserialize. However, from reading the documentation it's clear that Rust programs are supposed to be able to assume strings are valid UTF-8, so I'm fine if you close this.

**Comment by danburkert** [comment]
> However, from reading the documentation it's clear that Rust programs are supposed to be able to assume strings are valid UTF-8, so I'm fine if you close this.
