### ISSUE TITLE
proto3 fields should be optional (Option<T>), no ?

### ISSUE THREAD

**Issue by Rulliam** [danburkert/prost#350]
In the tutorial.rs example in the README , the generated rust code is : 

```rust
#[derive(Clone, Debug, PartialEq, Message)]
pub struct Person {
    #[prost(string, tag="1")]
    pub name: String,
    /// Unique ID number for this person.
    #[prost(int32, tag="2")]
    pub id: i32,
    #[prost(string, tag="3")]
    pub email: String,
    #[prost(message, repeated, tag="4")]
    pub phones: Vec<person::PhoneNumber>,
}
```

Why the `name` is not an `Option<String>` ? (and all other fields). According to proto3 specs, all fields should be optional by default, isn't it ?

Thank you

**Comment by praveenperera** [comment]
No in proton3 all fields will default to a set value if not passed in. Its extremely annoying to deal with.

For example if name isn't passed it it will default to `""` (empty string), ints will default to 0 so on an so forth.

Ref: https://developers.google.com/protocol-buffers/docs/proto3#default

**Comment by Rulliam** [comment]
I would have take advantage of rust Options, but ok
