### ISSUE TITLE
Support proto3 Field Presence

### ISSUE THREAD

**Issue by theduke** [danburkert/prost#351]
Field presence is a new experimental feature that adds support for `optional` fields. 

TLDR: it works in a somewhat hacky way by representing an optional field with a  `oneOf` with only one variant. 

https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md#satisfying-the-experimental-check

**Comment by danburkert** [comment]
This was implemented in #388.
