### ISSUE TITLE
Convert singleton `oneof` to `Option`?

### ISSUE THREAD

**Issue by praveenperera** [danburkert/prost#356]
Because proto3 got rid of optional fields, until they add them back in (#351)  I'm forced to do `oneof` everywhere.

Example: 

```protobuf
message Cmd {
  oneof timeout { int64 _timeout = 1; };                        // default=500
  oneof docker_image { string _docker_image = 2; };             // required
  oneof image_pull_secrets { string _image_pull_secrets = 3; }; // optional
  oneof namespace { string _namespace = 5; }        // default=default
  oneof backoff_limit { int32 _backoff_limit = 6; }  // optional
  oneof completions { int32 _completions = 7; } // optional
  map<string, string> annotations = 4;
}
```

I was wondering if in these cases Prost could automatically generate the struct with all the oneof fields being an `Option`

ex:

```rust
pub struct Cmd {
  timeout: Option<i32>
...
}
```

**Comment by danburkert** [comment]
This sounds like a good idea, as long as it’s exposed as a codegen option.

**Comment by danburkert** [comment]
#388 adds support for experimental proto3 optional fields.

**Comment by danburkert** [comment]
Incidentally, you can also use the wrapper types in `prost-types` to do this more elegantly than a single-valued `oneof`.  See these tests for the details: #391 .  As such I'm going to close this out, as I'm not in favor of the original ask (singleton `oneof`) since there are two good workarounds.
