### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by cpcloud** [danburkert/prost#357]
I'm looking to take advantage of https://github.com/danburkert/prost/commit/d9547f173246480e69120300f41c190257e0b63f in https://github.com/cpcloud/tensorflow_proto/pull/2, and it works like a charm.

Ideally though I wouldn't have to depend on a commit hash to pick up the necessary prost fix. Can a new release to crates.io be made?

**Comment by x1ddos** [comment]
Dup: https://github.com/danburkert/prost/issues/329

**Comment by cpcloud** [comment]
Closing as a duplicate.
