### ISSUE TITLE
Type Annotation Failures

### ISSUE THREAD

**Issue by dan-fritchman** [danburkert/prost#359]
Thanks a ton for your work on this! 

I can't seem to serialize my Rust-defined types, as written up in https://github.com/danburkert/prost#serializing-existing-types. This snippet from the README:

```rust
use prost::Message;

#[derive(Clone, Debug, PartialEq, Message)]
struct Person {
  pub id: String, // tag=1

  // NOTE: Old "name" field has been removed
  // pub name: String, // tag=2 (Removed)

  #[prost(tag="6")]
  pub given_name: String, // tag=6
  pub family_name: String, // tag=7
  pub formatted_name: String, // tag=8
}
```

Generates:

```
  |
4 | #[derive(Clone, Debug, PartialEq, Message)]
  |                                   ^^^^^^^
  |
  = help: message: called `Result::unwrap()` on an `Err` value: invalid message field Person.id
          
          Caused by:
              no type attribute
```

Adding the type-annotations inside the `prost` macro cures this. 
Am I missing something? My impression is that since #73, the un-annotated version should work. 
Thanks!

**Comment by dan-fritchman** [comment]
I should add: here are the Prost versions I'm using:

```toml

[dependencies]
prost = "0.6.1"
prost-types = "0.6.1"
# ... 

[build-dependencies]
prost-build = "0.6.1"
```

I believe they are the latest.

**Comment by danburkert** [comment]
Yeah it looks like the example in the README is wrong, thanks for pointing it out.  Type annotations are always necessary; that PR included type inference in a very early iteration, but it was removed because it's not robust.  The example should have been updated to include type annotations.

**Comment by dan-fritchman** [comment]
Sent quick, working update to the README example: #365.

**Comment by danburkert** [comment]
Thanks!
