### ISSUE TITLE
Rust Types -> Protoc -> Other Languages

### ISSUE THREAD

**Issue by dan-fritchman** [danburkert/prost#370]
Is there any way to get Rust-defined types which implement `prost::Message` out to `protoc`, so that it could generate code for other languages? (Or otherwise get a `.proto` schema-file out of them?) 

Example use-case would be something like the README ["serializing existing types"](https://github.com/danburkert/prost#serializing-existing-types) section. 

```rust
#[derive(Clone, Debug, PartialEq, Message)]
struct Person {
  pub id: String, // tag=1

  // NOTE: Old "name" field has been removed
  // pub name: String, // tag=2 (Removed)

  #[prost(tag="6")]
  pub given_name: String, // tag=6
  pub family_name: String, // tag=7
  pub formatted_name: String, // tag=8

  #[prost(tag="3")]
  pub age: u32, // tag=3
  pub height: u32, // tag=4
  #[prost(enumeration="Gender")]
  pub gender: i32, // tag=5

  // NOTE: Skip to less commonly occurring fields
  #[prost(tag="16")]
  pub name_prefix: String, // tag=16  (eg. mr/mrs/ms)
  pub name_suffix: String, // tag=17  (eg. jr/esq)
  pub maiden_name: String, // tag=18
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Enumeration)]
pub enum Gender {
  Unknown = 0,
  Female = 1,
  Male = 2,
}
```

This would be the "opposite" of what `compile_protos` does in a sense. 

Thanks much for the work on this!

**Comment by danburkert** [comment]
No, there is no support for this built-in to `prost`.  It would most likely require reflection capabilities, which is also currently missing from `prost`.  Ideally there'd be a way to do this outside of `prost` using such capabilities, but currently I don't think it's possible.

**Comment by danburkert** [comment]
Actually I'm not sure this would ever be supported.  It'd require some serious heavy lifting in `prost-derive`, and I'm not keen to make that code even more complex.

**Comment by dan-fritchman** [comment]
Thanks for following up. Closing.
