### ISSUE TITLE
Remove redundant value from oneof boolean fields

### ISSUE THREAD

**Issue by tvolk131** [danburkert/prost#372]
Let's say I have a protobuf message that has a **oneof** containing a boolean property. In my case it looks like this:

```
syntax = "proto3";

message GameConfig {
  // ...Other properties.

  oneof end_condition {
    // Once a player reaches this score, the game
    // is stopped automatically and that player wins.
    int32 max_score = 3;

    // The game never ends automatically.
    bool endless_mode = 4;
  }
}
```

If I want to unpack the **end_condition** property here from the generated code, I can do something like this:

```
    fn stringify_game_config_end_condition(game_config: &GameConfig) -> String {
        match game_config.end_condition {
            Some(end_condition) => {
                match end_condition {
                    EndCondition::MaxScore(max_score) => format!("Max score is {}.", max_score),
                    EndCondition::EndlessMode(endless_mode_enabled) => format!(
                      "Endless mode is set to {}.",
                      endless_mode_enabled
                    )
                }
            },
            None => String::from("Win condition is unset.")
        }
    }
```

This works fine, but since I'm using proto3, setting endless_mode to false is the same as unsetting it. So if we ever end up on line 6 of the Rust function above, we can guarantee that **endless_mode_enabled** is true. If it were false, it wouldn't have even entered the match statement on line 4 in the first place, and would instead have exited on line 12.

Is there any reason I didn't think of that we couldn't remove the enum value of boolean fields nested inside of **oneof**s?

**Comment by danburkert** [comment]
> This works fine, but since I'm using proto3, setting endless_mode to false is the same as unsetting it.

This is incorrect, in the context of a `oneof` field (it _is_ true in the context of a normal scalar field).  For your usecase, I'd recommend changing the type of `endless_mode` to `.google.protobuf.Empty`.  By default, `prost` substitutes the unit type (`()`) for `.google.protobuf.Empty`, so it's semantically saying that `endless_mode_enabled` is a data-less enum variant.

**Comment by tvolk131** [comment]
Sorry, just getting back to this. Thanks for taking a look, that makes sense!
