### ISSUE TITLE
Using compile_well_known_types() breaks rustdoc tests

### ISSUE THREAD

**Issue by greg-szabo** [danburkert/prost#374]
Dan, awesome work, you opened a new world for me with Prost!

I'm compiling the Google protobuf types using `Config::compile_well_known_types()` because I need to add extra annotations to it. Unfortunately, the Google comments are not very Rust-friendly and at around the "Examples" section of the `Timestamp` and `Duration` types' documentation, rustdoc starts interpreting them as code and chokes on them.

This makes the doctests fail and I couldn't find a way to ignore this doctest without editing the generated file. (In which case I could add `'''ignore` (but using back-ticks) or just remove the offending lines.) Maybe I'm missing something, in which case I'm happy to get a "Rust 1-0-1 lession".

This is not really a bug on `prost`'s part (the comments come from Google), but `prost` is in the unique situation of being able to easily fix it.

There are a few options I can think of, please implement something so doctest doesn't break.

1. Edit out the bad part of the comments on the `prost` side. I understand that might be problematic because it's so much easier to copy an upstream project`s files than manually editing them.
1. Do not include comments (documentation text) when running `compile_well_known_types()`. This must be easier but it's a bit lame that docs are not included.
1. Make it an option to not include documentation text so the developer can decide what is best for them.
1. Maybe even make it an option per-message. If it's not a hassle to implement it.
1. Optionally: allow `extern_path` for generated `prost_types` so I can reimplement the necessary types without invoking `compile_well_known_types()`.

My current workaround for anyone running into this problem is to 
* generate `Timestamp` and `Duration` myself
* use `compile_well_known_types()` to generate the protobuf types
* use `extern_path()` to replace the generated Timestamp and Duration with my own
This is a crude hack that uses a side-effect of `extern_path()`: `prost` will NOT generate the built-in `Timestamp` and `Duration` structs - and the invalid document text with them.

**Comment by danburkert** [comment]
Hey @greg-szabo, I've put up #389 as a possible solution to this problem.  Can you check out the example that's included in that PR and see if it works for your problem?

**Comment by danburkert** [comment]
Going to close this out since #389 is a good workaround for this issue.  For anyone following along, I don't consider the bit about `extern_path()` to be a hack - that's pretty much it's reason for existence.  The only thing `compile_well_known_types()` does is add the full set of WKT paths to `extern_path()`.
