### ISSUE TITLE
Implement Default on generated structs

### ISSUE THREAD

**Issue by fabricedesre** [danburkert/prost#40]
Message::clear() is resetting all fields to their default values already, but in some situations it would be nice to be able to just create a "cleared" object.

**Comment by danburkert** [comment]
`Default` is generated for each struct, and it takes into account the default attributes in the `.proto`  for proto2 (proto3 doesn't allow default values).  If you want to get a feel for what generated structs look like you can see examples in [`prost-types`](https://docs.rs/prost-types/0.2.0/prost_types/struct.DescriptorProto.html).

**Comment by fabricedesre** [comment]
You're right, thanks!
