### ISSUE TITLE
How to use serde Serialize with type_add?

### ISSUE THREAD

**Issue by ProjectMoon** [danburkert/prost#401]
The docs give an example of using `#[derive(Serialize)]` with type_attribute. However, when I do this, I get a cannot resolve macro error. I do have Serde as a build dependency.

```
    let mut config = prost_build::Config::new();
    config.type_attribute(".", "#[derive(Serialize)]");
    config.type_attribute(".", "#[serde(rename_all = \"camelCase\")]");
    config
        .compile_protos(&["proto/my.proto"], &["proto/"])
        .unwrap();
```

**Comment by ProjectMoon** [comment]
So I was able to get it working with `extern crate serde_derive` in the crate root. Is it possible to do this without having to declare `extern crate`?

**Comment by tmarkovski** [comment]
`.type_attribute(".", "#[derive(::serde::Serialize)]")`

**Comment by ProjectMoon** [comment]
I already tried that originally. The only thing it gives is this: `could not find `Serialize` in serde`

**Comment by vorner** [comment]
It works for me just fine. But serde has the proc macros as an optional dependency. Are you using the `derive` feature?

**Comment by ProjectMoon** [comment]
That was the trick. I had `serde_derive` declared as a dependency, but did not have the derive feature turned on. After I turned that on and removed serde_derive, I was able to get it all working.
