### ISSUE TITLE
Struct with bool encodes to empty array

### ISSUE THREAD

**Issue by JoNil** [danburkert/prost#402]
```rust
#[repr(C)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerStatsMessage {
    #[prost(bool, tag = "1")]
    pub decode_successful: bool,
}
```

when serializing this struct with decode_successful set to false i get a empty slice back.

I am then no able to de-serialize it back.

Is this intended?

**Comment by danburkert** [comment]
Yes this is intended, default values are not serialized.

**Comment by danburkert** [comment]
Closing this out, please reopen if you suspect there is a bug.
