### ISSUE TITLE
Oneof is a bit unwieldy

### ISSUE THREAD

**Issue by Jragonmiris** [danburkert/prost#41]
I have some deeply nested messages along the lines of

    message A {
        oneof specific {
             B b = 1;
             C c = 2;
        }
    }

    message B {
        oneof more_specific {
            E e = 1;
            F f = 2;
        }
    }

And so on, this is a... pain with prost. Currently, a OneOf is an option over an enum, meaning trying to do this involves repeated checks for malformed messages. It would perhaps be nice to allow an optional directive to `prost_build` and `prost_derive` to allow failure on decoding when a `oneof` isn't set instead of going the option route.

I say optional because I understand that it IS considered a possible field value in protobuf to help ease failure while decoding messages made with old formats, but it's a pretty big ergonomics issue even 2 or 3 nested levels deep.

**Comment by danburkert** [comment]
I went back and forth on whether `oneof` fields should be wrapped in an `Option`, or whether the `None` variant should be built-in to the enum type.  In the end I think `Option` is the right default.  

Between Rust's support for nested destructuring and the Option combinators I haven't personally run into a situation where it's too painful.  Do you have a code example?

> it IS considered a possible field value in protobuf to help ease failure while decoding messages made with old formats

Yeah this is pretty critical.  It's not just a backwards compatibility issue, but a _forwards_ compatibility issue as well.  It's nice to be able to remove fields that become obsolete in the future.

**Comment by Jragonmiris** [comment]
Sorry for the silence. I've been using it a bit more, and I do feel an `Unknown` option would be a bit better (note that this does have a potential issue with naming conflicts, if the oneof already has a variant with the same name).

This is adapted from code I have (with some minification like turning error handling into `panic` and such).

```
match self.specific_msg {
    //oneof
    Some(SpecificMsg::Config { 
        Cfg {
            // oneof
            which_module: Some (WhichModule::CoreCfg {
                plugin_type: PluginType{ plugin_type: /* oneof */ Some(ref mut plugin_type) },
             })
       }
    }) =>{ /* do things */ },
     Some(SpecificMsg::Config { 
        Cfg {
           which_module: Some (WhichModule::CoreCfg {
                plugin_type: PluginType{ plugin_type: /* oneof */  None},
             })
       }) => panic!("Invalid plugin_type"),
    Some(SpecificMsg::Config { 
        Cfg {
            which_module: None
       }) => panic!("This module doesn't handle this type of config"),
    None => panic!("Invalid variant denoting the specific message type"),
}
```

Compare this to

```
match self.specific_msg {
    SpecificMsg::Config { 
        Cfg {
            which_module: WhichModule::CoreCfg {
                plugin_type: PluginType{ plugin_type },
             }
       }
    } =>{ /* do things */ },
     SpecificMsg::Config { 
        Cfg {
           which_module: WhichModule::CoreCfg {
                plugin_type: PluginType{ plugin_type: OneOfEnum::Unknown},
             }
       }
    } => panic!("Invalid plugin_type"),
    SpecificMsg::Config { 
        Cfg {
            which_module: WhichModule::Unknown
         }
      } => panic!("This module doesn't handle this type of config"),
    SpecificMsg::Unknown => panic!("Invalid variant denoting the specific message type"),
}
```

There are more arms to that match, but I feel like it gets the gist across.

You can gussy both up a bit with `{ .. }` or `_` for the Unknown/None variants, but that introduces the danger of adding an extra variant you need to consider and not getting an error that it's not handled.

I feel like the latter is more readable. For one, matching the `Unknown` field it's clear what enum the `oneof` corresponds to, which the `Option` version doesn't clarify. Secondly, when destructuring a struct, you can just specify the field rather than the version `field: Some(ref mut field)` thing which can be significant verbosity for multi-member structs. In addition, paren matching can be a pain with that many open/close braces even when your editor helps.

Overall it's not the biggest issue, but I feel the non-option way is easier to parse by a bit.

This would also allow detection of messages that only occur in a message's `oneof` and "inlining" them so to speak.

So

```
message Foo {
    oneof foo_type {
        Bar bar = 1;
        Baz baz = 2;  
    }
}

Bar {
    required string a = 1;
}

Baz {
    oneof baz_type {
        int32 id = 1;
        float number = 2;
    }
}
```

Can be interpreted as

```
enum BazType {
    Id(int),
    Number(float),
    Unknown,
}

enum FooType {
    Bar { a: String },
    Baz { baz_type: BazType },
    Unknown
}

struct Foo {
    foo_type: FooType   
}
```

Which also reduces stutter a lot. This would allow the above to be

```
match self.specific_msg {
    SpecificMsg::Config { 
        which_module: WhichModule::CoreCfg {
            plugin_type: PluginType{ plugin_type },
        }
    } =>{ /* do things */ },
     SpecificMsg::Config { 
       which_module: WhichModule::CoreCfg {
            plugin_type: PluginType{ plugin_type: OneOfEnum::Unknown},
        }
    } => panic!("Invalid plugin_type"),
    SpecificMsg::Config { 
        which_module: WhichModule::Unknown
     } => panic!("This module doesn't handle this type of config"),
    SpecificMsg::Unknown => panic!("Invalid variant denoting the specific message type"),
}
```

**Comment by danburkert** [comment]
I've decided to leave `oneof` codegen the way it is, see the extended rational in #42.
