### ISSUE TITLE
Docs tweaks: how to install with macOS Silicon / ARM

### ISSUE THREAD

**Issue by Eric-Arellano** [danburkert/prost#420]
Hello, thanks for this excellent project!

Would you be open to a PR to tweak the docs to describe how to build with macOS Silicon? There isn't yet a pre-installed Protoc binary released through GitHub releases (https://github.com/protocolbuffers/protobuf/issues/8062), so I had to `brew install protobuf`. Looks like I didn't actually have to set `PROTOC` or `PROTOC_INCLUDE`; `protoc` being on the `$PATH` was sufficient iiuc.

I'd be happy to update some docs. Maybe these places?

- The below error message. We can maybe detect if on macOS ARM and if so, append a suggestion to install Protoc, e.g. via `brew install protobuf`?

```
Failed to find the protoc binary. The PROTOC environment variable is not set, there is no bundled protoc for this platform, and protoc is not in the PATH
```

- Maybe somewhere in the README, like https://github.com/danburkert/prost#using-prost-in-a-cargo-project
- https://docs.rs/prost-build/0.7.0/prost_build/index.html#sourcing-protoc

Also, the docs from https://docs.rs/prost-build/0.7.0/prost_build/index.html#sourcing-protoc give an example for how to set Protoc via homebrew, but it looks like Homebrew has (recently?) changed its default install dirs. I'm happy to update this.

```
PROTOC=/opt/homebrew/bin/protoc
PROTOC_INCLUDE=/opt/homebrew/include
```

Let me know what would be helpful!

**Comment by danburkert** [comment]
Are you running prost 0.6 or 0.7?   My understanding is that as of #394 prost-build should ‘just work’, and that PR is included in 0.7.  Happy to take a pr to update the brew example if it’s no longer accurate.

**Comment by danburkert** [comment]
Actually it appears the  /opt location is specific to arm macs: https://docs.brew.sh/Installation

**Comment by Eric-Arellano** [comment]
> Are you running prost 0.6 or 0.7?

Ah! Indeed, we're using Prost 0.6.1 over at https://github.com/pantsbuild/pants. Sorry I hadn't caught #394 earlier, great to see that included.

> Actually it appears the /opt location is specific to arm macs

Interesting, good catch. Thanks! The number of macOS Silicon users is so much lower that it makes sense to stick with the `/usr/local` path. Lmk if you'd like a tiny PR to clarify in those docs it's for Homebrew on macOS x86.

**Comment by Eric-Arellano** [comment]
Ah, another possibility for the Homebrew example:

```
PROTOC=$(brew --prefix)/bin/protoc
PROTOC_INCLUDE=$(brew --prefix)/include
```

**Comment by danburkert** [comment]
> Ah, another possibility for the Homebrew example:
