### ISSUE TITLE
How to share .proto messages across multiple microservices?

### ISSUE THREAD

**Issue by singerxt** [danburkert/prost#422]
I'm trying to create a bunch of microservices. Most grpc messages use this message
```
message i18n {   map<string, string> translations = 0; } 
```
i18n also implements additional methods to choose the right key for the request context. [In this way](https://github.com/danburkert/snazzy/blob/master/src/lib.rs)

I would like to create a Crate that will be stored in the private GitHub repository with proto and additional functionality so I can share i18n messages and logic across multiple microservices using cargo.
```
 // cargo.toml
[dependencies] i18n = { git = "url" branch= "main" } 
```
Is there any chance I can do it using [extern_path](https://github.com/danburkert/snazzy/blob/master/src/lib.rs)?

If not can you share your experience with prost library and how you were sharing code?

**Comment by danburkert** [comment]
Yep, this is what `extern_path` is for.  The method doc has a good example of this usecase.

**Comment by singerxt** [comment]
@danburkert thanks! 

What about _.proto_ files. Do you know how can I expose them from crate??

**Comment by danburkert** [comment]
`include_bytes!` maybe?  I'm not sure what the usecase for that would be.

**Comment by singerxt** [comment]
first of all, @danburkert thank you for your time.

My use case is that I would like to import crate like _snazzy_ as git dependency.

```
// cargo.toml
[dependencies]
snazzy = { git = "https://github.com/danburkert/snazzy" }
```

and use it at my project like this

```
syntax = "proto3";

package i18n;
import "snazzy.proto"; //originaly items.proto

message i18nString {
   snazzy.items.Shirt = 1;
}
```

**Comment by danburkert** [comment]
Ah I see.  I think you are going to have to vendor the .proto file in your project; there's no support for including external text files with Cargo as far as I know.

**Comment by singerxt** [comment]
Yeah!

Looks like I will have to copy the .proto file from across all microservices however I can share code what have methods for struct as a crate.

Did you experience a case like this before? Let me know if have any recommendations. Once I will resolve it I will write an article about a case like that because there is not much on StackOverflow, Reddit, medium about that ;-)

**Comment by danburkert** [comment]
Another option is to download the .proto in a build script if you want to avoid vendoring.
