### ISSUE TITLE
proto3 optional

### ISSUE THREAD

**Issue by cemoktra** [danburkert/prost#430]
In documentation you write:

`The table of field modifiers above applies to message fields, except that proto3 message fields without a modifier (the default) will be wrapped in an Option`

But that's not true in my case. Leaving all modifiers will not create an option for me. The only way to do so is use proto2 and optional modifier

**Comment by danburkert** [comment]
I believe the statement as written is correct.  What field type are you seeing this behavior with?

**Comment by cemoktra** [comment]
Hi. Actually it was just a message with a combination of required and optional int64

**Comment by grippy** [comment]
@danburkert I'm seeing something and I can't tell from the README text highlighted by @cemoktra if this is expected...

For this example:

```
syntax = "proto3";

message A { string val = 1; }
message B { string val = 1; }
message C { A a = 1; }
message Example {
  A a = 1;
  B b = 2;
  optional C c = 3;
}
```

Produces this output:

```
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct A {
    #[prost(string, tag = "1")]
    pub val: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct B {
    #[prost(string, tag = "1")]
    pub val: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct C {
    #[prost(message, optional, tag = "1")]
    pub a: ::core::option::Option<A>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Example {
    #[prost(message, optional, tag = "1")]
    pub a: ::core::option::Option<A>,
    #[prost(message, optional, tag = "2")]
    pub b: ::core::option::Option<B>,
    #[prost(message, optional, tag = "3")]
    pub c: ::core::option::Option<C>,
}
```

The generated files have message fields wrapped as Option<T> for fields that aren't defined as `optional`. This only happens for message types that aren't defined as prost strings, though. Is this expected?

**Comment by danburkert** [comment]
> The generated files have message fields wrapped as Option for fields that aren't defined as optional. This only happens for message types that aren't defined as prost strings, though. Is this expected?

I believe this is expected, but I'm not sure what you mean by 'message types that aren't defined as prost strings' - messages and strings are separate types.

**Comment by grippy** [comment]
@danburkert Whoops, sorry. This was supposed to be "message field types that aren't defined as strings". For example, they don't end up as `Option<::prost::alloc::string::String>` when they aren't defined as optional -- while `C.a`, which is also not defined as optional, does end up as `Option<A>`. Thanks for clarifying.

**Comment by danburkert** [comment]
I see - yes it's expected.  As the README notes, proto3 message fields without a modifier are be wrapped in an `Option`.  The new proto3 `optional` modifier is for scalar fields, I'm kind of surprised `protoc` even lets you apply it to a message field.

**Comment by sfackler** [comment]
> I'm kind of surprised `protoc` even lets you apply it to a message field.

Even if it doesn't change behavior in the actual generated code, it can document to developers which fields are actually expected to be sometimes unset and which are expected to always be present.

**Comment by sfackler** [comment]
It looks like the new proto3 `optional` works just fine with prost 0.7. I think this can be closed?

**Comment by sfackler** [comment]
Scratch that, prost_build panics with more complex message definitions using optional.

**Comment by threema-danilo** [comment]
Since protoco 3.15, `optional` is not experimental anymore: https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0

Would be nice to bump the bundled protoc for the next release.
