### ISSUE TITLE
Generated code can't find types from other protobuf packages.

### ISSUE THREAD

**Issue by gorzell** [danburkert/prost#440]
Apologies in advance if I somehow missed something in the docs or other issues, I did look through them to see if I could find anything that was similar to this error.

It seems like the code for imports within a protobuf file is correctly identified and generated, but when that code is in a different protobuf package, that locations/imports/use/FQN are not generated correctly to link them together.  The end result is that you get compile time errors because `super` is used too many times:
```
error[E0433]: failed to resolve: there are too many leading `super` keywords
 --> /home/gorzell/src/github/gorzell/prost-cross-package-import/target/debug/build/prost-cross-package-import-63a1798d87160e99/out/test.main.v1.rs:4:39
  |
4 |     pub other: ::core::option::Option<super::super::other::v1::Other>,
  |                                       ^^^^^ there are too many leading `super` keywords

error[E0283]: type annotations needed
 --> /home/gorzell/src/github/gorzell/prost-cross-package-import/target/debug/build/prost-cross-package-import-63a1798d87160e99/out/test.main.v1.rs:1:28
  |
1 | #[derive(Clone, PartialEq, ::prost::Message)]
  |                            ^^^^^^^^^^^^^^^^ cannot infer type
  |
  = note: cannot satisfy `_: Default`
  = note: required by `std::default::Default::default`
```

## Reproduction
The full code for a simple reproduction case can be found in: https://github.com/gorzell/prost-cross-package-import.

For reference the proto files look like the following.

`proto/main/v1/main.proto`
```proto
syntax = "proto3";

package test.main.v1;

import "other/v1/other.proto";

message Main {
  test.other.v1.Other other = 1;
}
```

`proto/other/v1/other.proto`
```proto
syntax = "proto3";

package test.other.v1;

message Other {
  string foo = 1;
}
```
Hopefully this is something simple I am missing, if not I am happy to try and dig into the code a bit more and see if I can find the root cause.

**Comment by gorzell** [comment]
I looked into the code a bit today and I think I have narrowed the issue down to the following: https://github.com/danburkert/prost/blob/master/prost-build/src/code_generator.rs#L782-L786

```rust
 local_path
            .map(|_| "super".to_string())
            .chain(ident_path.map(to_snake))
            .chain(iter::once(to_upper_camel(ident_type)))
            .join("::")
```
This appears to assume that there will always be **only one** sub-package difference between two files. i.e.
`test.main` and `test.other` would work fine (leaving just `main` and `other` after processing. On the other hand `test.main.v1` and `test.other.v1` leave you with `["main", "v1"] or ["other", "v1"] still in the `local_path` after processing. If you then call `map(|_| "super".to_string())` you replace both with `super` so after all the chaining, and the join you end up with `super::super::other::v1::Other`.

I am not yet confident enough in my understanding of the code generation to know what the appropriate way to fix this is though.  I think that ideally you would just use a fully qualified `crate::` based reference for everything, rather than trying to use `super::`.

**Comment by danburkert** [comment]
@gorzell I believe the issue with your repro repo is that you need a two `include!` calls, one for each package.  See https://github.com/danburkert/prost/tree/master/tests/src/packages for an example.

**Comment by gorzell** [comment]
@danburkert thanks for the reply and the pointer.  I took a look at that test and I think that in many cases it provides a solution to:
> Note: Because the Rust module structure doesn't align with the proto package structure, there is also a bug/case where if you had messages with the same name in different proto packages (which is as far as I know a legal/reasonable thing to do) that Rust types would end up colliding.

However, I don't think that it addresses the fundamental bug where, which is that there is invalid Rust code generated by `prost-build`.  The test case while having more nesting still shares a base name that will generate only one `super` and that `super` will be valid.  There are other possible package namespaces for which this will not work, which is what I am trying to demonstrate in the repro repo.  I have updated the code there to reflect the suggestions and better align with your sample code.

I don't actually control the proto files that I am trying to consume, so I can't force them into the pattern that works.  I believe that these other package/namespace structures are valid and they seem to work fine in Go/Ruby/Java.

**Comment by danburkert** [comment]
@gorzell I think you are overthinking this, there is no `prost` bug.  Try this:

**Comment by gorzell** [comment]
Happy to try that when I am back at my computer.  I hope I am over thinking it, I am just struggling to understand how changing the includes is going to resolve the fact that the generated code in `test.main.v1.rs` has this:

```

error[E0433]: failed to resolve: there are too many leading `super` keywords
 --> /home/gorzell/src/github/gorzell/prost-cross-package-import/target/debug/build/prost-cross-package-import-63a1798d87160e99/out/test.main.v1.rs:4:39
  |
4 |     pub other: ::core::option::Option<super::super::other::v1::Other>,
```

I don't think there is any context in which `super::super::other` is valid Rust syntax.

**Comment by danburkert** [comment]
It's definitely valid Rust syntax.  I'm having trouble pinpointing where you might be confused, but for reference `super::super::other::v1::Other` path symbol, which is looking two modules 'up' for an `other` module containing a `v1` module.  `prost` requires you to set up your Rust modules with the same relative paths as your .proto packages.  That's why the fix is to add the missing rust module corresponding to the `main` module.

**Comment by danburkert** [comment]
(`super` is a Rust keyword)

**Comment by gorzell** [comment]
Thanks for the patience.  My confusion was with the compiler message and a false assumption (perhaps from other languages) that you could move up via relative paths more than one time.  Knowing that syntax can be valid makes everything else make sense.  Thanks again.

**Comment by Adoni5** [comment]
Thanks guys, just resolved a couple of hours of grief that I was having!

**Comment by JonathanWilbur** [comment]
Just a thought: if prost absolutely depends on these modules having a fixed placement with respect to each other, why not just generate the mod-mod file as well?

In other words, if it compiles two modules `foo` and `bar`, why not also produce this?

```rust
pub mod foo {
    include!(concat!(env!("OUT_DIR"), "/foo.rs"));
}

pub mod bar {
    include!(concat!(env!("OUT_DIR"), "/bar.rs"));
}
```

**Comment by caspermeijn** [comment]
> Just a thought: if prost absolutely depends on these modules having a fixed placement with respect to each other, why not just generate the mod-mod file as well?

It actually has that feature: https://docs.rs/prost-build/latest/prost_build/struct.Config.html#method.include_file

If this comment is useful to you, please consider opening a PR with documentation changes. So that this feature is documented in the place where you began your search.
