### ISSUE TITLE
Documentation when to use `compile_well_known_types`

### ISSUE THREAD

**Issue by haoadoresorange** [danburkert/prost#452]
Hello,

This is not exactly an issue, so I'm sorry if this is not the right place for the post.

I recently learned about `prost`. I noticed that when using well-known types I can either use the `prost-types` crate or just compile from original `.proto` file with `compile_well_known_types`. I look into the crate and see there's a couple differences in rust generated code from what compiled with the `.proto`, for example the `Any` type not using `Bytes`.

I've been searching but found not much thing regarding the matter. Is there any particular reason for the differences in `prost-types` implementation ? advantage ? when and why should I favour it ?

I found Dan's reasoning about why using `prost-types` here https://github.com/danburkert/prost/issues/228#issuecomment-573352125 but I don't really get it.

Thanks very much for the responses.

**Comment by danburkert** [comment]
You shouldn't use the `compile_well_known_types` configuration unless you have a specific reason.  Sorry this isn't a satisfying answer, but this configuration is an escape hatch for niche usecases, and I don't think it's that useful to enumerate hypothetical examples (even if I could).
