### ISSUE TITLE
#![no_std] for prost

### ISSUE THREAD

**Issue by ameets** [danburkert/prost#51]
Hi @danburkert, do you have any plans to make prost compatible with `no_std`?

**Comment by ameets** [comment]
@danburkert,  I'm going to revive [this PR](https://github.com/danburkert/prost/pull/22) for `no_std` support. If you have any further thoughts aside from the initial review please let me know.

**Comment by danburkert** [comment]
Sounds good.  Don't have any other thoughts at the moment, but I'm sure I will when it becomes more fleshed out.

**Comment by jrozner** [comment]
would just like to say that this would be extremely useful for me. I'm interested in using rust with microcontrollers to replace some of the c/c++ I'm currently writing and have been using nanopb in those environments. It works reasonably well but being able to move the micro code over would be nice.

**Comment by kthakore** [comment]
@jrozner were you ever able to get this work.

I am using 0.7.0 but prost-build still makes `::std::collections` versus `alloc`

**Comment by danburkert** [comment]
@kthakore maybe you need to switch to using BTreeMap instead of HashMap?  See   I'm going to close this issue out since no_std support is landed.  Please. open a new issue with more details if you suspect there is a bug in the implementation.
