### ISSUE TITLE
Would it support service

### ISSUE THREAD

**Issue by AndreMouche** [danburkert/prost#53]
Would it support `service` one  day, it seems not work for the following situation:

```
syntax = "proto3";
package grpc;

service HelloService {
  rpc SayHello (HelloRequest) returns (HelloResponse);
}

message HelloRequest {
  string greeting = 1;
}

message HelloResponse {
  string reply = 1;
}

```

**Comment by danburkert** [comment]
Are you asking about `grpc` in particular?  `prost` isn't a `grpc` implementation.  If you're asking about services in general, you can already register your own code generator for service: https://docs.rs/prost-build/0.2.3/prost_build/struct.Config.html#method.service_generator.

**Comment by AndreMouche** [comment]
got it, thanks very much
