### ISSUE TITLE
CLI containers needs kubectl

### ISSUE THREAD

**Issue by olix0r** [danburkert/prost#55]
the cli container can fail to run because `kubectl` isn't installed.

Do we even need a CLI container since we have the artifacts one (from which the CLI can be extracted)?

**Comment by danburkert** [comment]
Was this filed on the wrong repo?  Otherwise I think the description is missing some context.

**Comment by olix0r** [comment]
Yes, my apologies. the browser bar really wants me to file prost issues for some reason
