### ISSUE TITLE
Option in Proto3

### ISSUE THREAD

**Issue by cramertj** [danburkert/prost#64]
The [field modifiers](https://github.com/danburkert/prost#field-modifiers) section of the README explains that `optional` proto2 fields are wrapped in `Option`, while required fields and proto3 fields are not. This seems strange to me because the default in proto3 should correspond to `optional`, not `required`. It was determined that `required` fields should be used sparingly, so they were removed completely in proto3.

In PROST's proto3 deserialization, are missing fields converted to default values of the given type, or does deserialization fail?

**Comment by danburkert** [comment]
Missing fields are converted to the default value for the type.  It's not really true that scalar/primitive proto3 fields correspond to proto2's `optional`, since you don't get the `has_` methods.

**Comment by cramertj** [comment]
@danburkert That's true, I should have said that they are *not* like `required`, rather than that they *are* like `optional`. Thanks for clarifying and thanks for your work on PROST! It seems great so far.
