### ISSUE TITLE
Document Enumerations

### ISSUE THREAD

**Issue by dvtomas** [danburkert/prost#69]
README says:

*All .proto enumeration types convert to the Rust i32 type. Additionally, each enumeration type gets a corresponding Rust enum type, with helper methods to convert i32 values to the enum type. The enum type isn't used directly as a field, because the Protobuf spec mandates that enumerations values are 'open', and decoding unrecognized enumeration values must be possible.*

It took me some (rather cheerless) time to discover that I can convert an enumeration like the one in the README example

```rust
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Enumeration)]
    pub enum PhoneType {
        Mobile = 0,
        Home = 1,
        Work = 2,
    }
```

to the value this way:

```rust
PhoneType::Mobile as i32
```

However, for the opposite direction, I'm lost for good. How do I convert an i32 code to PhoneType? Where do I find those "helper methods to convert i32 values to the enum type"? I'd really appreciate an example in the README. Thank you.

Furthermore, what is the `#[derive(Enumeration)]` ? Can't find the Enumeration trait anywhere..

**Comment by danburkert** [comment]
Hi @dvtomas, thanks for opening this issue, I agree the docs should be improved in this area.  The ergonomic helpers for enums were added after I wrote that bit in the readme, and I never went back and filled it in.

Toward your immediate issue, the best way to see what's available is to run `rustdoc` on the types and see the methods which they expose.  In the case of a `PhoneType` enum, it will expose a pair of methods which help convert from `i32`:

```rust
impl PhoneType {
  pub fn is_valid(value: i32) -> bool;
  pub fn from_i32(value: i32) -> Option<PhoneType>;
}
```

You can see a concrete example [here](https://docs.rs/prost-types/0.2.3/prost_types/field/enum.Cardinality.html).

As for the `Enumeration` trait, there is actually no such thing.  `derive(Enumeration)` is a trick which allows prost to generate these methods for enum types, but there's no corresponding trait.

I'm going to leave this issue open to track improving the enum docs.

**Comment by danburkert** [comment]
Forgot to mention - there are other helper methods as well.  Wherever an Enumeration is used as a field in a Message, the message will have an 'accessor' methods to get/set the value as the proper type.  For instance, the [`Field`](https://docs.rs/prost-types/0.2.3/prost_types/struct.Field.html) struct contains a `Cardinality` field and the following methods:

```rust
impl Field {
  pub fn cardinality(&self) -> Cardinality;
  pub fn set_cardinality(&mut self, value: Cardinality);
}
```

Note that the first of these will return the default value (the first variant if otherwise unspecified) if the `i32` value is out of range.

**Comment by dvtomas** [comment]
Thank you for the info! It's a neat trick to use rustdoc, I didn't know it also documents derived and macro-generated code.

**Comment by sdbondi** [comment]
How about `From<i32>` be implemented for enums?

So that this would work:

```rust
match phone_type.into() {
   PhoneType::Mobile => {},
  // etc.    
  _ => {}
}
```

**Comment by markmandel** [comment]
Can someone please provide an example on how to do do the `rustdoc` trick? I'm scouring documentation, and I can't seem to find the right combination of arguments :disappointed: 

I was hoping that `cargo doc --open --document-private-items` would do the job, but seems like it's not the case.

(Although the comments above definitely helped!, so thank you for that!)
