### ISSUE TITLE
Consider generating idiomatic enum value names

### ISSUE THREAD

**Issue by warrenfalk** [danburkert/prost#80]
Idiomatic protocol buffer definitions for enums is to prefix the enum value names with the name of the enum.  This is because in protocol buffers, the enum value names are in the same namespace as the enum itself (which means you aren't allowed to have two different values named ```GOOD``` even if they are in different enums.  And therefore this is common and idiomatic in protocol buffers:

```protobuf
enum ResultCode {
    RESULT_CODE_GOOD = 0;
    RESULT_CODE_BAD = 1;
    RESULT_CODE_UGLY = 2;
}
```

Rust doesn't suffer from this unfortunate design and so if you were to code the same thing in idiomatic Rust, it would look like this:

```rust
enum ResultCode {
    Good = 0,
    Bad = 1,
    Ugly = 2,
}
```

Not like this:

```rust
enum ResultCode {
    ResultCodeGood = 0,
    ResultCodeBad = 1,
    ResultCodeUgly = 2,
}
```

And you'll find that all of the newer "official" protocol buffer generators do this (take C# for example). 
They will detect if the enum value names are prefixed with the enum's name and strip it off if so.

I've already written this behavior for Prost, controlled by config and will send a PR in case you're interested.  Currently it defaults to existing behavior, but I think you might want to consider making idiomatic Rust the default behavior.  For those who don't prefix their protobuf enum value names, well they won't notice either way, and for those that do, they'll probably appreciate the improvement to their code.

**Comment by briansmith** [comment]
Rather than having an option to control this, maybe we should just do this by default in a new major version of prost.

**Comment by danburkert** [comment]
This was by @warrenfalk in a87d216f1190cebce507ebd1bdb48fe91e652c0b.
