### ISSUE TITLE
Hash, Ord and PartialOrd for enums

### ISSUE THREAD

**Issue by vorner** [danburkert/prost#86]
Hello

The generated enum types that are generated for protobuffer enums don't implement `Hash`, `PartialOrd` nor `Ord`. As these are simple enums (without data inside their variants), there doesn't seem to be a reason for that (or maybe I just don't see it).

It would be handy to be able to use them as part of keys in hash maps or btree maps, which this makes harder. I guess I could use their numeric representation, but in case I already went through, validated the message and keep only extracted data (as the enums, for easier manipulation in Rust), this makes it harder.

Would it be OK to add them? Should I try doing it?

**Comment by danburkert** [comment]
This is a good idea.  I'm going to work on this, I think it should be very straightforward.

**Comment by ebkalderon** [comment]
I'm very happy to see this feature implemented. Something that I'm currently working on needs enums defined in Protobuf to implement `Hash`, `Ord`, and `PartialOrd` since they are being used as part of a `HashMap` key. Will this feature be released soon?
