### ISSUE TITLE
Remove requirement for package declaration in .proto

### ISSUE THREAD

**Issue by vlisivka** [danburkert/prost#91]
> Currently, all .proto files used with prost must contain a package declaration. prost will translate the Protobuf package into a Rust module. For example, given the package declaration:
> 
> package foo.bar;
> 
> All Rust types generated from the file will be in the foo::bar module.

It's not true: no module statement is generated. Moreover, it works fine without module statement, because it's easy to add it later, in main code.

Please, remove requirement form package declaration, because it causes interoperability problem. I need to copy .proto file into temporary file, edit in place, then generate .rs files from it. Default to file names instead of package names, please.

**Comment by vlisivka** [comment]
It's looks reasonable. Can you add then an option to proto compiler for top-level package (file) name when it is omitted in the .proto file?

If not, then copying of files and appending "package foo;" to end of file is good workaround, which is worth to be mentioned in prost-build documentation.

**Comment by danburkert** [comment]
I'm going to close this out, because I don't know of a way to remove the requirement for package declarations.  Feel free to re-open if you have a proposal.

**Comment by tylerhawkes** [comment]
@LucioFranco can we get someone to take a look at https://github.com/tokio-rs/prost/pull/343 to see if we can get this resolved?
