### ISSUE TITLE
Compilation on ARM v7 on Raspberry Pi

### ISSUE THREAD

**Issue by ChristopherRabotin** [danburkert/prost#94]
I'm trying to compile a demo of using protobufs on a Raspberry Pi.

I get an error saying that the `PROTOC` and `PROTOC_INCLUDE` environment variables are not set, and armv7 isn't a platform with a native protoc library. I'm currently compiling `protobuf` version 3.5.1 on the Pi. Once I have that compiled, what should I point these environment variables to?

Thanks

**Comment by danburkert** [comment]
Hi @ChristopherRabotin, sorry for the slow reply.  You can find docs on those environment variables [here](https://docs.rs/prost-build/0.3.2/prost_build/#sourcing-protoc).  This issue also made me realize that we can streamline this process somewhat for platforms which don't bundle `protoc` by checking the `PATH`.  #95 introduces that behavior if you want to try it out.

**Comment by ChristopherRabotin** [comment]
No worries. I actually should have closed this issue since I got it to compile like a charm by simply setting those environment variables to the folder where I had the build for `protoc` on the Pi.
