### ISSUE TITLE
Buffer underflow for repeating the same message over TCP?

### ISSUE THREAD

**Issue by ChristopherRabotin** [danburkert/prost#98]
I'm encountering an odd situation which does not seem to make sense to me.

One thread is a TcpListener. Another is a TcpStream which connects to that TcpListener. When I send one encoded PB to the Listener, the listener reacts as it should, and responds correctly. If I send the exact same PB again to the same listener on a new connection for a **second** time, it also works. Repeating this a third time however (it's a `for` loop with 10 iterations), I get a `buffer underflow` error.

Any idea how this can happen? If needed, I can write up some demo code (the code I have which currently does this is likely considered proprietary sadly).

Here's a log of this program (I can share that). The messages preceded by `[DEMO]` are printed by the thread which send the PB to the listener several times.
```
> RUST_LOG=info ./target/release/goats 1590 --test
 INFO  goats > Listening on TCP port 127.0.0.1:1590
 INFO  goats > Running test #0
 INFO  goats > [DEMO] Sending 74 bytes to TCP listener
 INFO  goats > Received 74 bytes from 127.0.0.1:35936
 INFO  goats > Decoding received data
 INFO  goats > [DEMO] Received 63 bytes from 127.0.0.1:1590
 INFO  goats > [DEMO] Decoding response
State { datetime: 58112.04391203704, x: -2127.471563378845, y: -2737.7856037111474, z: 6880.2288479000645, x_dot: 5.207976990871051, y_dot: -4.953282710438696, z_dot: -0.36017724766516945 }
State { datetime: 58112.04391203704, x: -2127.471563378845, y: -2737.7856037111474, z: 6880.2288479000645, x_dot: 5.207976990871051, y_dot: -4.953282710438696, z_dot: -0.36017724766516945 }
 INFO  goats > Done in Duration { secs: 0, nanos: 1921582 }: State { datetime: 58112.04391203704, x: -2127.471563378845, y: -2737.7856037111474, z: 6880.2288479000645, x_dot: 5.207976990871051, y_dot: -4.953282710438696, z_dot: -0.36017724766516945 }
 INFO  goats > Running test #1
 INFO  goats > [DEMO] Sending 74 bytes to TCP listener
 INFO  goats > Received 74 bytes from 127.0.0.1:35938
 INFO  goats > Decoding received data
 INFO  goats > [DEMO] Received 126 bytes from 127.0.0.1:1590
 INFO  goats > [DEMO] Decoding response
State { datetime: 58112.04391203704, x: -2127.471563378845, y: -2737.7856037111474, z: 6880.2288479000645, x_dot: 5.207976990871051, y_dot: -4.953282710438696, z_dot: -0.36017724766516945 }
State { datetime: 58112.04391203704, x: -2127.471563378845, y: -2737.7856037111474, z: 6880.2288479000645, x_dot: 5.207976990871051, y_dot: -4.953282710438696, z_dot: -0.36017724766516945 }
 INFO  goats > Done in Duration { secs: 0, nanos: 3665367 }: State { datetime: 58112.04391203704, x: -2127.471563378845, y: -2737.7856037111474, z: 6880.2288479000645, x_dot: 5.207976990871051, y_dot: -4.953282710438696, z_dot: -0.36017724766516945 }
 INFO  goats > Running test #2
 INFO  goats > [DEMO] Sending 74 bytes to TCP listener
 INFO  goats > Received 74 bytes from 127.0.0.1:35940
 INFO  goats > Decoding received data
 INFO  goats > [DEMO] Received 128 bytes from 127.0.0.1:1590
 INFO  goats > [DEMO] Decoding response
thread 'main' panicked at 'could not decode response DecodeError { description: "buffer underflow", stack: [("State", "datetime")] }', src/main.rs:170:27
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Also, here are the PB definitions I'm using:
```
syntax = "proto3";
package sttr.comms;

message State {
  double datetime = 1;
  double x = 2;
  double y = 3;
  double z = 4;
  double x_dot = 5;
  double y_dot = 6;
  double z_dot = 7;
}

message PropInfo {
  State init = 1;
  double GM = 2;
  double prop_time = 3;
}
```

**Comment by ChristopherRabotin** [comment]
Looking at the logs, it seems that the amount of bytes received keeps on increasing. Yet, here's the relevant receiving code, which exists within a for loop:

```
            // Read the response.
            let mut buf = [0; 128];
            let amt = socket.read(&mut buf).expect("ugh");
            info!(
                "[DEMO] Received {} bytes from {}",
                amt,
                socket.peer_addr().expect("how?")
            );
            let mut dec_buffer = Bytes::with_capacity(amt);
            dec_buffer.extend_from_slice(&buf);
            dec_buffer.truncate(amt);
```

**Comment by danburkert** [comment]
Are you clearing the write buffer in between each call to encode?

**Comment by ChristopherRabotin** [comment]
No, I'm not. But it's declared within the for loop, so I was expecting that it would be clearer at each iteration automatically as a new allocation.

**Comment by danburkert** [comment]
Could you provide the code that encodes the message and writes it to the socket?

Also, it doesn't appear that you are using any kind of length delimiting, which is typically necessary when sending multiple messages across a stream.

**Comment by danburkert** [comment]
See these links for info about length delimiting messages in streams:

https://developers.google.com/protocol-buffers/docs/techniques#streaming
https://docs.rs/prost/0.3.2/prost/trait.Message.html#method.encode_length_delimited
https://docs.rs/prost/0.3.2/prost/trait.Message.html#method.decode_length_delimited

I'm not sure what you mean about truncating.

**Comment by ChristopherRabotin** [comment]
Your insight was on the nose! First, I was not using `length_delimited` as I should have, and secondly, my response buffer was initialized _before_ the loop which handled the incoming connections. Thanks for your help, the Rust backend works now (onto the C sender now).
